title: Environment
path: environment
icon: mdi:earth
cards:
  - type: entities
    title: Astronomy
    show_header_toggle: false
    entities:
      - sensor.period_of_day
      - sun.sun
      - sensor.moon
      - sensor.season
      - sensor.date
      - sensor.time
  - type: entities
    title: Meteorology
    show_header_toggle: false
    entities:
      - sensor.openweathermap_condition
      - sensor.openweathermap_temperature
      - sensor.openweathermap_humidity
      - sensor.openweathermap_pressure
      - sensor.openweathermap_wind_speed
      - sensor.openweathermap_wind_bearing
      - sensor.openweathermap_visibility
      - sensor.openweathermap_uv_index
