title: Environment
path: environment
icon: mdi:earth
cards:
  - type: entities
    title: Astronomy
    show_header_toggle: false
    entities:
      - sensor.period_of_day
      - sun.sun
      - sensor.moon
      - sensor.season
      - sensor.date
      - sensor.time
  - type: entities
    title: Meteorology
    show_header_toggle: false
    entities:
      - type: attribute
        entity: weather.meteorologisk
        attribute: temperature
        name: Temperature
        unit: '°C'
        icon: mdi:thermometer
      - type: attribute
        entity: weather.meteorologisk
        attribute: humidity
        name: Humidity
        unit: '%'
        icon: mdi:water-percent
      - type: attribute
        entity: weather.meteorologisk
        attribute: pressure
        name: Pressure
        unit: hPa
        icon: mdi:thermometer-lines
      - type: attribute
        entity: weather.meteorologisk
        attribute: dew_point
        name: Dew Point
        unit: '°C'
        icon: mdi:thermometer-water
      - type: attribute
        entity: weather.meteorologisk
        attribute: wind_speed
        name: Wind Speed
        unit: 'km/h'
        icon: mdi:weather-windy
      - type: attribute
        entity: weather.meteorologisk
        attribute: wind_bearing
        name: Wind Bearing
        unit: '°'
        icon: mdi:compass
      - type: attribute
        entity: weather.meteorologisk
        attribute: uv_index
        name: UV Index
        icon: mdi:sun-wireless
