language: python
python:
  - '3.7'
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit
before_install:
  - python --version
  - pip install -U pip
install:
  - pip install -r requirements_test.txt
before_script:
  - mv secrets_dummy.yaml secrets.yaml
script:
  - pre-commit install-hooks
  - pre-commit run yamllint --all-files
  - hass -c . --script check_config
