language: python
python:
  - '3.5'
  - '3.6'
env:
  - HASS=0.67.1
before_install:
  - mv secrets_dummy.yaml secrets.yaml
install:
  - pip3 install homeassistant==$HASS
script:
  - hass -c . --script check_config
