language: python
python:
  - '3.7'
  - '3.8'
env:
  - GCTTS=0.4.0 HASS=0.100.0
before_install:
  - mv secrets_dummy.yaml secrets.yaml
install:
  - pip3 install yamllint
  - pip3 install google-cloud-texttospeech==$GCTTS
  - pip3 install homeassistant==$HASS
script:
  - yamllint .
  - hass -c . --script check_config
