dist: bionic
language: python
python:
  - '3.9'
  - '3.10'
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit
before_install:
  - pip install -U pip
install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
before_script:
  - mv secrets_dummy.yaml secrets.yaml
  - pre-commit install-hooks
script:
  - pre-commit run yamllint --all-files
  - hass -c . --script check_config
