- alias: 'Turn Outdoor Frontdoor Light on at Sunset'
  trigger:
    platform: sun
    event: sunset
    offset: '-00:20:00'
  action:
    - delay: '00:{{ (range(0, 11) | random) }}:00'
    - service: light.turn_on
      data:
        entity_id: light.outdoor_frontdoor_light

- alias: 'Turn Outdoor Lights off in the Night'
  trigger:
    platform: time
    at: '00:00:00'
  action:
    - delay: '00:{{ (range(0, 60) | random) }}:00'
    - service: light.turn_off
      data:
        entity_id: group.outdoor_lights

- alias: 'Arrive Home at Day'
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'not_home'
    to: 'home'
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunrise
        after_offset: '2:00:00'
      - condition: sun
        before: sunset
        before_offset: '-2:00:00'
  action:
    - service: automation.turn_off
      data:
        entity_id: automation.simulate_occupancy
    - service: scene.turn_on
      data:
        entity_id: scene.arrive_home_at_day

- alias: 'Arrive Home at Night'
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'not_home'
    to: 'home'
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: '-2:00:00'
      - condition: sun
        before: sunrise
        before_offset: '2:00:00'
  action:
    - service: automation.turn_off
      data:
        entity_id: automation.simulate_occupancy
    - service: scene.turn_on
      data:
        entity_id: scene.arrive_home_at_night

- alias: 'Leave Home at Day'
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'home'
    to: 'not_home'
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunrise
        after_offset: '2:00:00'
      - condition: sun
        before: sunset
        before_offset: '-2:00:00'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.leave_home_at_day
    - service: automation.turn_on
      data:
        entity_id: automation.simulate_occupancy

- alias: 'Leave Home at Night'
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'home'
    to: 'not_home'
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: '-2:00:00'
      - condition: sun
        before: sunrise
        before_offset: '2:00:00'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.leave_home_at_night
    - service: automation.turn_on
      data:
        entity_id: automation.simulate_occupancy

- alias: 'Simulate Occupancy'
  initial_state: false
  trigger:
    platform: time
    minutes: '/30'
    seconds: '00'
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: '-02:00:00'
      - condition: time
        before: '01:00:00'
  action:
    - delay: '00:{{ (range(0, 16) | random) }}:00'
    - service: scene.turn_on
      data_template:
        entity_id: 'scene.occupancy_simulation_{{ (range(1, 4) | random) }}'
