- alias: 'Turn Outdoor Frontdoor Light on at Sunset'
  trigger:
    platform: sun
    event: sunset
    offset: '-00:20:00'
  action:
    - delay: '00:{{ (range(0, 11) | random) }}:00'
    - service: light.turn_on
      data:
        entity_id: light.outdoor_frontdoor_light

- alias: 'Turn Outdoor Lights off in the Night'
  trigger:
    platform: time
    at: '00:00:00'
  action:
    - delay: '00:{{ (range(0, 60) | random) }}:00'
    - service: light.turn_off
      data:
        entity_id: group.outdoor_lights

- alias: 'Arrive Home at Day'
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'not_home'
    to: 'home'
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunrise
        after_offset: '2:00:00'
      - condition: sun
        before: sunset
        before_offset: '-2:00:00'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.away_mode
    - service: scene.turn_on
      data:
        entity_id: scene.arrive_home_at_day

- alias: 'Arrive Home at Night'
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'not_home'
    to: 'home'
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: '-2:00:00'
      - condition: sun
        before: sunrise
        before_offset: '2:00:00'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.away_mode
    - service: scene.turn_on
      data:
        entity_id: scene.arrive_home_at_night

- alias: 'Leave Home at Day'
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'home'
    to: 'not_home'
  condition:
    condition: and
    conditions:
      - condition: sun
        after: sunrise
        after_offset: '2:00:00'
      - condition: sun
        before: sunset
        before_offset: '-2:00:00'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.leave_home_at_day
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.away_mode

- alias: 'Leave Home at Night'
  trigger:
    platform: state
    entity_id: group.all_devices
    from: 'home'
    to: 'not_home'
  condition:
    condition: or
    conditions:
      - condition: sun
        after: sunset
        after_offset: '-2:00:00'
      - condition: sun
        before: sunrise
        before_offset: '2:00:00'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.leave_home_at_night
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.away_mode

- alias: 'Start Occupancy Simulation'
  trigger:
    - platform: state
      entity_id: input_boolean.away_mode
      from: 'off'
      to: 'on'
    - platform: sun
      event: sunset
      offset: '-02:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'on'
      - condition: or
        conditions:
          - condition: sun
            after: sunset
            after_offset: '-02:00:00'
          - condition: time
            before: '01:00:00'
  action:
    - service: script.turn_on
      data:
        entity_id: script.occupancy_simulation_start

- alias: 'Stop Occupancy Simulation'
  trigger:
    - platform: state
      entity_id: input_boolean.away_mode
      from: 'on'
      to: 'off'
    - platform: time
      at: '01:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'
      - condition: or
        conditions:
          - condition: sun
            after: sunset
            after_offset: '-02:00:00'
          - condition: time
            before: '01:00:00'
  action:
    - service: script.turn_on
      data:
        entity_id: script.occupancy_simulation_stop

- alias: 'Enable: Say Good Morning'
  trigger:
    - platform: time
      at: '06:00:00'
  action:
    - service: automation.turn_on
      data:
        entity_id: automation.say_good_morning

- alias: 'Disable: Say Good Morning'
  trigger:
    - platform: time
      at: '12:00:00'
  action:
    - service: automation.turn_off
      data:
        entity_id: automation.say_good_morning

- alias: 'Say Good Morning'
  trigger:
    platform: mqtt
    topic: 'smarty/esp8266-376566/button1'
  action:
    - delay: '00:00:05'
    - service: script.sonos_say
      data_template:
        sonos_say_volume: '0.3'
        sonos_say_message: >
          {{ [
          "Einen guten Morgen David!",
          "Guten Morgen David!",
          "Hallo David!"
          ] | random }}
        sonos_say_delay: '00:00:02'
    - service: automation.turn_off
      data:
        entity_id: automation.say_good_morning
