- platform: mqtt
  state_topic: 'smarty/esp8266-377332/$online'
  name: 'Outdoor Frontdoor Light Connectivity'
  payload_on: 'true'
  payload_off: 'false'
- platform: mqtt
  state_topic: 'smarty/esp8266-3dbc1d/$online'
  name: 'Outdoor Backdoor Light Connectivity'
  payload_on: 'true'
  payload_off: 'false'
- platform: mqtt
  state_topic: 'smarty/esp8266-376566/$online'
  name: 'Kitchen Ceiling Light Connectivity'
  payload_on: 'true'
  payload_off: 'false'
- platform: mqtt
  state_topic: 'smarty/esp8266-9541f4/$online'
  name: 'Kitchen Sideboard Light Connectivity'
  payload_on: 'true'
  payload_off: 'false'
- platform: mqtt
  state_topic: 'smarty/esp8266-f94d00/$online'
  name: 'Kitchen Cabinet Light Connectivity'
  payload_on: 'true'
  payload_off: 'false'
- platform: mqtt
  state_topic: 'smarty/esp8266-826269/$online'
  name: 'Living Room Ceiling Light Connectivity'
  payload_on: 'true'
  payload_off: 'false'
- platform: mqtt
  state_topic: 'smarty/esp8266-afc031/$online'
  name: 'Living Room Sofa Light Connectivity'
  payload_on: 'true'
  payload_off: 'false'
- platform: mqtt
  state_topic: 'smarty/esp8266-3e7098/$online'
  name: 'Bedroom Ceiling Light Connectivity'
  payload_on: 'true'
  payload_off: 'false'
- platform: mqtt
  state_topic: 'smarty/esp8266-95791a/$online'
  name: 'Bedroom Bed Light Connectivity'
  payload_on: 'true'
  payload_off: 'false'
- platform: mqtt
  state_topic: 'smarty/esp8266-95d69b/$online'
  name: 'Bedroom Ambient Light Connectivity'
  payload_on: 'true'
  payload_off: 'false'
- platform: mqtt
  state_topic: 'smarty/esp8266-121bb3/$online'
  name: 'Hall Ceiling Light Connectivity'
  payload_on: 'true'
  payload_off: 'false'
