all_input_booleans:
  name: all input booleans
  entities:
    - input_boolean.away_mode

all_scenes:
  name: all scenes
  entities:
    - scene.all_indoor_lights_off
    - scene.all_indoor_lights_on
    - scene.all_lights_off
    - scene.all_lights_on
    - scene.arrive_home_at_day
    - scene.arrive_home_at_night
    - scene.leave_home_at_day
    - scene.leave_home_at_night
    - scene.occupancy_simulation_0
    - scene.occupancy_simulation_1
    - scene.occupancy_simulation_2
    - scene.occupancy_simulation_3

outdoor_lights:
  name: Outdoor Lights
  entities:
    - light.outdoor_frontdoor_light
    - light.outdoor_backdoor_light
kitchen_lights:
  name: Kitchen Lights
  entities:
    - light.kitchen_ceiling_light
    - light.kitchen_sideboard_light
    - light.kitchen_cabinet_light
living_room_lights:
  name: Living Room Lights
  entities:
    - light.living_room_ceiling_light
    - light.living_room_sofa_light
bedroom_lights:
  name: Bedroom Lights
  entities:
    - light.bedroom_ceiling_light
    - light.bedroom_bed_light
hall_lights:
  name: Hall Lights
  entities:
    - light.hall_ceiling_light

outdoor:
  name: Outdoor
  entities:
    - light.outdoor_frontdoor_light
    - light.outdoor_backdoor_light
kitchen:
  name: Kitchen
  entities:
    - light.kitchen_ceiling_light
    - light.kitchen_sideboard_light
    - light.kitchen_cabinet_light
living_room:
  name: Living Room
  entities:
    - light.living_room_ceiling_light
    - light.living_room_sofa_light
bedroom:
  name: Bedroom
  entities:
    - light.bedroom_ceiling_light
    - light.bedroom_bed_light
hall:
  name: Hall
  entities:
    - light.hall_ceiling_light

weather:
  name: Weather
  entities:
    - sun.sun
    - sensor.moon
    - sensor.owm_condition
    - sensor.owm_forecast
    - sensor.owm_temperature
    - sensor.owm_humidity
    - sensor.owm_cloud_coverage
    - sensor.owm_pressure

internet:
  name: Internet
  entities:
    - sensor.fritz_netmonitor
    - sensor.fritz_bytes_received
    - sensor.fritz_bytes_sent

raspberry_pi:
  name: Raspberry Pi
  entities:
    - sensor.load_1m
    - sensor.load_5m
    - sensor.load_15m
    - sensor.processor_use
    - sensor.memory_use_percent
    - sensor.disk_use_percent_
    - sensor.since_last_boot

homeassistant:
  name: Home Assistant
  entities:
    - sensor.uptime

smarty:
  name: Smarty Devices
  entities:
    - binary_sensor.outdoor_frontdoor_light_connectivity
    - sensor.outdoor_frontdoor_light_uptime
    - sensor.outdoor_frontdoor_light_firmware
    - sensor.outdoor_frontdoor_light_wifi_ip
    - sensor.outdoor_frontdoor_light_wifi_rssi
    - binary_sensor.outdoor_backdoor_light_connectivity
    - sensor.outdoor_backdoor_light_uptime
    - sensor.outdoor_backdoor_light_firmware
    - sensor.outdoor_backdoor_light_wifi_ip
    - sensor.outdoor_backdoor_light_wifi_rssi
    - binary_sensor.kitchen_ceiling_light_connectivity
    - sensor.kitchen_ceiling_light_uptime
    - sensor.kitchen_ceiling_light_firmware
    - sensor.kitchen_ceiling_light_wifi_ip
    - sensor.kitchen_ceiling_light_wifi_rssi
    - binary_sensor.kitchen_sideboard_light_connectivity
    - sensor.kitchen_sideboard_light_uptime
    - sensor.kitchen_sideboard_light_firmware
    - sensor.kitchen_sideboard_light_wifi_ip
    - sensor.kitchen_sideboard_light_wifi_rssi
    - binary_sensor.kitchen_cabinet_light_connectivity
    - sensor.kitchen_cabinet_light_uptime
    - sensor.kitchen_cabinet_light_firmware
    - sensor.kitchen_cabinet_light_wifi_ip
    - sensor.kitchen_cabinet_light_wifi_rssi
    - binary_sensor.living_room_ceiling_light_connectivity
    - sensor.living_room_ceiling_light_uptime
    - sensor.living_room_ceiling_light_firmware
    - sensor.living_room_ceiling_light_wifi_ip
    - sensor.living_room_ceiling_light_wifi_rssi
    - binary_sensor.living_room_sofa_light_connectivity
    - sensor.living_room_sofa_light_uptime
    - sensor.living_room_sofa_light_firmware
    - sensor.living_room_sofa_light_wifi_ip
    - sensor.living_room_sofa_light_wifi_rssi
    - binary_sensor.hall_ceiling_light_connectivity
    - sensor.hall_ceiling_light_uptime
    - sensor.hall_ceiling_light_firmware
    - sensor.hall_ceiling_light_wifi_ip
    - sensor.hall_ceiling_light_wifi_rssi

default_view:
  view: yes
  entities:
    - updater.updater
    - sensor.owm_temperature
    - device_tracker.david_nexus5x
    - input_boolean.away_mode
    - script.bedtime

rooms_view:
  name: Rooms
  view: yes
  entities:
    - group.outdoor
    - group.kitchen
    - group.living_room
    - group.bedroom
    - group.hall

environment_view:
  name: Environment
  view: yes
  entities:
    - group.weather

system_view:
  name: System
  view: yes
  entities:
    - group.internet
    - group.raspberry_pi
    - group.homeassistant
    - group.smarty

configuration_view:
  name: Configuration
  view: yes
  entities:
    - group.all_automations
    - group.all_input_booleans
    - group.all_scenes
    - group.all_scripts

development_view:
  name: Development
  view: yes
  entities:
    - switch.development_module_relay
