- platform: mqtt
  name: 'Outdoor Frontdoor Light'
  state_topic: 'smarty/esp8266-3775be/relay1'
  command_topic: 'smarty/esp8266-3775be/relay1/set'
  payload_on: '1'
  payload_off: '0'
- platform: mqtt
  name: 'Outdoor Backdoor Light'
  state_topic: 'smarty/dummy-1/relay1'
  command_topic: 'smarty/dummy-1/relay1/set'
  payload_on: '1'
  payload_off: '0'
- platform: mqtt
  name: 'Kitchen Ceiling Light'
  state_topic: 'smarty/esp8266-376566/relay1'
  command_topic: 'smarty/esp8266-376566/relay1/set'
  payload_on: '1'
  payload_off: '0'
- platform: mqtt
  name: 'Kitchen Sideboard Light'
  state_topic: 'smarty/esp8266-954045/relay1'
  command_topic: 'smarty/esp8266-954045/relay1/set'
  payload_on: '1'
  payload_off: '0'
- platform: mqtt
  name: 'Living Room Ceiling Light'
  state_topic: 'smarty/esp8266-826269/relay1'
  command_topic: 'smarty/esp8266-826269/relay1/set'
  payload_on: '1'
  payload_off: '0'
- platform: mqtt
  name: 'Living Room Sofa Light'
  state_topic: 'smarty/esp8266-afc031/relay1'
  command_topic: 'smarty/esp8266-afc031/relay1/set'
  payload_on: '1'
  payload_off: '0'
- platform: mqtt
  name: 'Bedroom Ceiling Light'
  state_topic: 'smarty/dummy-5/relay1'
  command_topic: 'smarty/dummy-5/relay1/set'
  payload_on: '1'
  payload_off: '0'
- platform: mqtt
  name: 'Bedroom Bed Light'
  state_topic: 'smarty/dummy-6/relay1'
  command_topic: 'smarty/dummy-6/relay1/set'
  payload_on: '1'
  payload_off: '0'
- platform: mqtt
  name: 'Bedroom Ambience Light'
  state_topic: 'smarty/esp8266-f94d00/relay1'
  command_topic: 'smarty/esp8266-f94d00/relay1/set'
  payload_on: '1'
  payload_off: '0'
- platform: mqtt
  name: 'Hall Ceiling Light'
  state_topic: 'smarty/esp8266-121bb3/relay1'
  command_topic: 'smarty/esp8266-121bb3/relay1/set'
  payload_on: '1'
  payload_off: '0'
