- platform: mqtt
  name: 'Outdoor Frontdoor Light'
  state_topic: 'smarty/esp8266-377332/relay1'
  command_topic: 'smarty/esp8266-377332/relay1/set'
  payload_on: '1'
  payload_off: '0'
- platform: mqtt
  name: 'Outdoor Backdoor Light'
  state_topic: 'smarty/esp8266-3dbc1d/relay1'
  command_topic: 'smarty/esp8266-3dbc1d/relay1/set'
  payload_on: '1'
  payload_off: '0'
- platform: mqtt
  name: 'Kitchen Ceiling Light'
  state_topic: 'smarty/esp8266-376566/relay1'
  command_topic: 'smarty/esp8266-376566/relay1/set'
  payload_on: '1'
  payload_off: '0'
- platform: mqtt
  name: 'Kitchen Sideboard Light'
  state_topic: 'smarty/esp8266-9541f4/relay1'
  command_topic: 'smarty/esp8266-9541f4/relay1/set'
  payload_on: '1'
  payload_off: '0'
- platform: mqtt
  name: 'Kitchen Cabinet Light'
  state_topic: 'smarty/esp8266-f94d00/relay1'
  command_topic: 'smarty/esp8266-f94d00/relay1/set'
  payload_on: '1'
  payload_off: '0'
- platform: mqtt
  name: 'Living Room Ceiling Light'
  state_topic: 'smarty/esp8266-826269/relay1'
  command_topic: 'smarty/esp8266-826269/relay1/set'
  payload_on: '1'
  payload_off: '0'
- platform: mqtt
  name: 'Living Room Sofa Light'
  state_topic: 'smarty/esp8266-afc031/relay1'
  command_topic: 'smarty/esp8266-afc031/relay1/set'
  payload_on: '1'
  payload_off: '0'
- platform: mqtt
  name: 'Bedroom Ceiling Light'
  state_topic: 'smarty/esp8266-3e7098/relay1'
  command_topic: 'smarty/esp8266-3e7098/relay1/set'
  payload_on: '1'
  payload_off: '0'
- platform: mqtt
  name: 'Bedroom Bed Light'
  state_topic: 'smarty/esp8266-95791a/relay1'
  command_topic: 'smarty/esp8266-95791a/relay1/set'
  payload_on: '1'
  payload_off: '0'
- platform: mqtt
  name: 'Bedroom Ambient Light'
  state_topic: 'smarty/esp8266-95d69b/relay1'
  command_topic: 'smarty/esp8266-95d69b/relay1/set'
  payload_on: '1'
  payload_off: '0'
- platform: mqtt
  name: 'Hall Ceiling Light'
  state_topic: 'smarty/esp8266-121bb3/relay1'
  command_topic: 'smarty/esp8266-121bb3/relay1/set'
  payload_on: '1'
  payload_off: '0'
