exclude = "^custom_components/"

[[repos]]
repo = "builtin"
hooks = [
  { id = "check-json" },
  { id = "check-merge-conflict" },
  { id = "check-toml" },
  { id = "check-yaml" },
  { id = "end-of-file-fixer" },
  { id = "fix-byte-order-marker" },
  { id = "mixed-line-ending" },
  { id = "trailing-whitespace" },
]

[[repos]]
repo = "https://github.com/adrienverge/yamllint.git"
rev = "v1.38.0"
hooks = [
  { id = "yamllint" },
]
