- platform: moon
- platform: openweathermap
  api_key: !secret openweathermap_api_key
  forecast: true
  monitored_conditions:
    - clouds
    - humidity
    - pressure
    - temperature
    - weather
- platform: systemmonitor
  resources:
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: processor_use
    - type: memory_use_percent
    - type: disk_use_percent
      arg: /
    - type: since_last_boot
- platform: uptime

- platform: mqtt
  state_topic: 'smarty/esp8266-377332/$system'
  name: 'Outdoor Frontdoor Light Uptime'
  expire_after: '660'
  value_template: '{{now().replace(tzinfo=None) - now().fromtimestamp(as_timestamp(now()) - float(value_json.uptime)) }}'
- platform: mqtt
  state_topic: 'smarty/esp8266-377332/$system'
  name: 'Outdoor Frontdoor Light Firmware'
  expire_after: '660'
  value_template: '{{ value_json["firmware"]["version"] }}'
- platform: mqtt
  state_topic: 'smarty/esp8266-377332/$system'
  name: 'Outdoor Frontdoor Light WiFi RSSI'
  unit_of_measurement: '%'
  expire_after: '660'
  value_template: '{{ (float(value_json["wifi"]["rssi"]) + 100) * 2 }}'
- platform: mqtt
  state_topic: 'smarty/esp8266-377332/$system'
  name: 'Outdoor Frontdoor Light WiFi IP'
  expire_after: '660'
  value_template: '{{ value_json["wifi"]["ip"] }}'

- platform: mqtt
  state_topic: 'smarty/esp8266-3e7098/$system'
  name: 'Outdoor Backdoor Light Uptime'
  expire_after: '660'
  value_template: '{{now().replace(tzinfo=None) - now().fromtimestamp(as_timestamp(now()) - float(value_json.uptime)) }}'
- platform: mqtt
  state_topic: 'smarty/esp8266-3e7098/$system'
  name: 'Outdoor Backdoor Light Firmware'
  expire_after: '660'
  value_template: '{{ value_json["firmware"]["version"] }}'
- platform: mqtt
  state_topic: 'smarty/esp8266-3e7098/$system'
  name: 'Outdoor Backdoor Light WiFi RSSI'
  unit_of_measurement: '%'
  expire_after: '660'
  value_template: '{{ (float(value_json["wifi"]["rssi"]) + 100) * 2 }}'
- platform: mqtt
  state_topic: 'smarty/esp8266-3e7098/$system'
  name: 'Outdoor Backdoor Light WiFi IP'
  expire_after: '660'
  value_template: '{{ value_json["wifi"]["ip"] }}'

- platform: mqtt
  state_topic: 'smarty/esp8266-376566/$system'
  name: 'Kitchen Ceiling Light Uptime'
  expire_after: '660'
  value_template: '{{now().replace(tzinfo=None) - now().fromtimestamp(as_timestamp(now()) - float(value_json.uptime)) }}'
- platform: mqtt
  state_topic: 'smarty/esp8266-376566/$system'
  name: 'Kitchen Ceiling Light Firmware'
  expire_after: '660'
  value_template: '{{ value_json["firmware"]["version"] }}'
- platform: mqtt
  state_topic: 'smarty/esp8266-376566/$system'
  name: 'Kitchen Ceiling Light WiFi RSSI'
  unit_of_measurement: '%'
  expire_after: '660'
  value_template: '{{ (float(value_json["wifi"]["rssi"]) + 100) * 2 }}'
- platform: mqtt
  state_topic: 'smarty/esp8266-376566/$system'
  name: 'Kitchen Ceiling Light WiFi IP'
  expire_after: '660'
  value_template: '{{ value_json["wifi"]["ip"] }}'

- platform: mqtt
  state_topic: 'smarty/esp8266-954045/$system'
  name: 'Kitchen Sideboard Light Uptime'
  expire_after: '660'
  value_template: '{{now().replace(tzinfo=None) - now().fromtimestamp(as_timestamp(now()) - float(value_json.uptime)) }}'
- platform: mqtt
  state_topic: 'smarty/esp8266-954045/$system'
  name: 'Kitchen Sideboard Light Firmware'
  expire_after: '660'
  value_template: '{{ value_json["firmware"]["version"] }}'
- platform: mqtt
  state_topic: 'smarty/esp8266-954045/$system'
  name: 'Kitchen Sideboard Light WiFi RSSI'
  unit_of_measurement: '%'
  expire_after: '660'
  value_template: '{{ (float(value_json["wifi"]["rssi"]) + 100) * 2 }}'
- platform: mqtt
  state_topic: 'smarty/esp8266-954045/$system'
  name: 'Kitchen Sideboard Light WiFi IP'
  expire_after: '660'
  value_template: '{{ value_json["wifi"]["ip"] }}'

- platform: mqtt
  state_topic: 'smarty/esp8266-f94d00/$system'
  name: 'Kitchen Cabinet Light Uptime'
  expire_after: '660'
  value_template: '{{now().replace(tzinfo=None) - now().fromtimestamp(as_timestamp(now()) - float(value_json.uptime)) }}'
- platform: mqtt
  state_topic: 'smarty/esp8266-f94d00/$system'
  name: 'Kitchen Cabinet Light Firmware'
  expire_after: '660'
  value_template: '{{ value_json["firmware"]["version"] }}'
- platform: mqtt
  state_topic: 'smarty/esp8266-f94d00/$system'
  name: 'Kitchen Cabinet Light WiFi RSSI'
  unit_of_measurement: '%'
  expire_after: '660'
  value_template: '{{ (float(value_json["wifi"]["rssi"]) + 100) * 2 }}'
- platform: mqtt
  state_topic: 'smarty/esp8266-f94d00/$system'
  name: 'Kitchen Cabinet Light WiFi IP'
  expire_after: '660'
  value_template: '{{ value_json["wifi"]["ip"] }}'

- platform: mqtt
  state_topic: 'smarty/esp8266-826269/$system'
  name: 'Living Room Ceiling Light Uptime'
  expire_after: '660'
  value_template: '{{now().replace(tzinfo=None) - now().fromtimestamp(as_timestamp(now()) - float(value_json.uptime)) }}'
- platform: mqtt
  state_topic: 'smarty/esp8266-826269/$system'
  name: 'Living Room Ceiling Light Firmware'
  expire_after: '660'
  value_template: '{{ value_json["firmware"]["version"] }}'
- platform: mqtt
  state_topic: 'smarty/esp8266-826269/$system'
  name: 'Living Room Ceiling Light WiFi RSSI'
  unit_of_measurement: '%'
  expire_after: '660'
  value_template: '{{ (float(value_json["wifi"]["rssi"]) + 100) * 2 }}'
- platform: mqtt
  state_topic: 'smarty/esp8266-826269/$system'
  name: 'Living Room Ceiling Light WiFi IP'
  expire_after: '660'
  value_template: '{{ value_json["wifi"]["ip"] }}'

- platform: mqtt
  state_topic: 'smarty/esp8266-afc031/$system'
  name: 'Living Room Sofa Light Uptime'
  expire_after: '660'
  value_template: '{{now().replace(tzinfo=None) - now().fromtimestamp(as_timestamp(now()) - float(value_json.uptime)) }}'
- platform: mqtt
  state_topic: 'smarty/esp8266-afc031/$system'
  name: 'Living Room Sofa Light Firmware'
  expire_after: '660'
  value_template: '{{ value_json["firmware"]["version"] }}'
- platform: mqtt
  state_topic: 'smarty/esp8266-afc031/$system'
  name: 'Living Room Sofa Light WiFi RSSI'
  unit_of_measurement: '%'
  expire_after: '660'
  value_template: '{{ (float(value_json["wifi"]["rssi"]) + 100) * 2 }}'
- platform: mqtt
  state_topic: 'smarty/esp8266-afc031/$system'
  name: 'Living Room Sofa Light WiFi IP'
  expire_after: '660'
  value_template: '{{ value_json["wifi"]["ip"] }}'

- platform: mqtt
  state_topic: 'smarty/esp8266-121bb3/$system'
  name: 'Hall Ceiling Light Uptime'
  expire_after: '660'
  value_template: '{{now().replace(tzinfo=None) - now().fromtimestamp(as_timestamp(now()) - float(value_json.uptime)) }}'
- platform: mqtt
  state_topic: 'smarty/esp8266-121bb3/$system'
  name: 'Hall Ceiling Light Firmware'
  expire_after: '660'
  value_template: '{{ value_json["firmware"]["version"] }}'
- platform: mqtt
  state_topic: 'smarty/esp8266-121bb3/$system'
  name: 'Hall Ceiling Light WiFi RSSI'
  unit_of_measurement: '%'
  expire_after: '660'
  value_template: '{{ (float(value_json["wifi"]["rssi"]) + 100) * 2 }}'
- platform: mqtt
  state_topic: 'smarty/esp8266-121bb3/$system'
  name: 'Hall Ceiling Light WiFi IP'
  expire_after: '660'
  value_template: '{{ value_json["wifi"]["ip"] }}'

- platform: template
  sensors:
    period_of_day:
      value_template: >-
        {% if (as_timestamp(states.sun.sun.attributes.next_dusk)) - (as_timestamp(states.sun.sun.attributes.next_setting)) < 0 %}
          Dusk
        {% elif (as_timestamp(states.sun.sun.attributes.next_rising)) - (as_timestamp(states.sun.sun.attributes.next_dawn)) < 0 %}
          Dawn
        {% elif (states.sun.sun.attributes.elevation) < 0 %}
          Night
        {% else %}
          Day
        {% endif %}
      icon_template: >-
        {% if is_state('sun.sun', 'above_horizon') %}
          mdi:weather-sunny
        {% else %}
          mdi:weather-night
        {% endif %}
