- platform: group
  name: Ambient Lights
  entities:
    - light.kitchen_sideboard_light
    - light.living_room_sofa_light
    - light.living_room_tv_light

- platform: group
  name: Bedroom Lights
  entities:
    - light.bedroom_ceiling_light
    - light.bedroom_bed_light
    - light.bedroom_cabinet_light
    - light.bedroom_dresser_light

- platform: group
  name: Hall Lights
  entities:
    - light.hall_ceiling_light

- platform: group
  name: Kitchen Lights
  entities:
    - light.kitchen_ceiling_light
    - light.kitchen_counter_light
    - light.kitchen_sideboard_light

- platform: group
  name: Living Room Lights
  entities:
    - light.living_room_ceiling_light
    - light.living_room_ambient_light
    - light.living_room_sofa_light
    - light.living_room_tv_light

- platform: group
  name: Outdoor Lights
  entities:
    - light.outdoor_frontdoor_light
    - light.outdoor_backdoor_light

- platform: group
  name: Presence Simulation Lights
  entities:
    - light.bedroom_ceiling_light
    - light.hall_ceiling_light
    - light.kitchen_ceiling_light
    - light.living_room_ceiling_light
    - light.outdoor_frontdoor_light
    - light.outdoor_backdoor_light
