- platform: mqtt
  name: bedroom_bed_light
  state_topic: "zigbee2mqtt/bedroom_bed_light"
  command_topic: "zigbee2mqtt/bedroom_bed_light/set"
  availability_topic: "zigbee2mqtt/bridge/state"
  schema: json
  brightness: true
  brightness_scale: 254
  color_mode: true
  supported_color_modes:
    - "color_temp"
  max_mireds: 500
  min_mireds: 150
  effect: true
  effect_list:
    - blink
    - breathe
    - okay
    - channel_change
    - finish_effect
    - stop_effect

- platform: mqtt
  name: kitchen_counter_light
  state_topic: "zigbee2mqtt/kitchen_counter_light"
  command_topic: "zigbee2mqtt/kitchen_counter_light/set"
  availability_topic: "zigbee2mqtt/bridge/state"
  schema: json
  brightness: true
  brightness_scale: 254
  color_mode: true
  supported_color_modes:
    - "color_temp"
  max_mireds: 454
  min_mireds: 250
  effect: true
  effect_list:
    - blink
    - breathe
    - okay
    - channel_change
    - finish_effect
    - stop_effect

- platform: mqtt
  name: living_room_sofa_light
  state_topic: "zigbee2mqtt/living_room_sofa_light"
  command_topic: "zigbee2mqtt/living_room_sofa_light/set"
  availability_topic: "zigbee2mqtt/bridge/state"
  schema: json
  brightness: true
  brightness_scale: 254
  color_mode: true
  supported_color_modes:
    - "color_temp"
    - "xy"
  max_mireds: 500
  min_mireds: 150
  effect: true
  effect_list:
    - blink
    - breathe
    - okay
    - channel_change
    - finish_effect
    - stop_effect
