- platform: time_date
  display_options:
    - 'date'
    - 'time'

- platform: moon

- platform: template
  sensors:
    period_of_day:
      value_template: >-
        {% if (as_timestamp(states.sun.sun.attributes.next_dusk)) - (as_timestamp(states.sun.sun.attributes.next_setting)) < 0 %}
          Dusk
        {% elif (as_timestamp(states.sun.sun.attributes.next_rising)) - (as_timestamp(states.sun.sun.attributes.next_dawn)) < 0 %}
          Dawn
        {% elif (states.sun.sun.attributes.elevation) < 0 %}
          Night
        {% else %}
          Day
        {% endif %}
      icon_template: >-
        {% if is_state('sun.sun', 'above_horizon') %}
          mdi:weather-sunny
        {% else %}
          mdi:weather-night
        {% endif %}
