- platform: time_date
  display_options:
    - 'date'
    - 'time'

- platform: template
  sensors:
    period_of_day:
      value_template: >-
        {% if state_attr('sun.sun', 'elevation') < -6 %}
          Night
        {% elif state_attr('sun.sun', 'elevation') < 0 and state_attr('sun.sun', 'rising') %}
          Dawn
        {% elif state_attr('sun.sun', 'elevation') < 0 and not state_attr('sun.sun', 'rising') %}
          Dusk
        {% elif state_attr('sun.sun', 'elevation') < 6 and state_attr('sun.sun', 'rising') %}
          Sunrise
        {% elif state_attr('sun.sun', 'elevation') < 6 and not state_attr('sun.sun', 'rising') %}
          Sunset
        {% else %}
          Day
        {% endif %}
      icon_template: >-
        {% if is_state('sun.sun', 'above_horizon') %}
          mdi:weather-sunny
        {% else %}
          mdi:weather-night
        {% endif %}
