- platform: time_date
  display_options:
    - 'date'
    - 'time'

- platform: season

- platform: moon

- platform: template
  sensors:
    period_of_day:
      value_template: >-
        {% if states.sun.sun.attributes.elevation < -6 %}
          Night
        {% elif states.sun.sun.attributes.elevation < 0 and states.sun.sun.attributes.rising %}
          Dawn
        {% elif states.sun.sun.attributes.elevation < 0 and not states.sun.sun.attributes.rising %}
          Dusk
        {% elif states.sun.sun.attributes.elevation < 6 and states.sun.sun.attributes.rising %}
          Sunrise
        {% elif states.sun.sun.attributes.elevation < 6 and not states.sun.sun.attributes.rising %}
          Sunset
        {% else %}
          Day
        {% endif %}
      icon_template: >-
        {% if is_state('sun.sun', 'above_horizon') %}
          mdi:weather-sunny
        {% else %}
          mdi:weather-night
        {% endif %}
