- platform: history_stats
  name: history stats away mode
  entity_id: input_boolean.away_mode
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: history stats bed mode
  entity_id: input_select.bed_mode
  state:
    - 'on'
    - 'just on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: history stats bedroom window left
  entity_id: binary_sensor.bedroom_window_left_contact
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: history stats bedroom window right
  entity_id: binary_sensor.bedroom_window_right_contact
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: history stats outdoor frontdoor
  entity_id: binary_sensor.outdoor_frontdoor_contact
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: history stats outdoor backdoor
  entity_id: binary_sensor.outdoor_backdoor_contact
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'

- platform: history_stats
  name: history stats kitchen coffee machine relay
  entity_id: switch.kitchen_coffee_machine_relay
  state: 'on'
  type: time
  start: '{{ now().replace(hour=0, minute=0, second=0) }}'
  end: '{{ now() }}'
