- platform: template
  sensors:
    boulderado_gym_opening:
      friendly_name: Boulderado Gym Opening
      value_template: >-
        {% if now().weekday() in (0,) %}
          {{ iif(today_at("14:30") <= now() <= today_at("23:00"), "open", "closed") }}
        {% elif now().weekday() in (1,) %}
          {{ iif(today_at("14:30") <= now() <= today_at("23:00"), "open", "closed") }}
        {% elif now().weekday() in (2,) %}
          {{ iif(today_at("14:30") <= now() <= today_at("23:00"), "open", "closed") }}
        {% elif now().weekday() in (3,) %}
          {{ iif(today_at("14:30") <= now() <= today_at("23:00"), "open", "closed") }}
        {% elif now().weekday() in (4,) %}
          {{ iif(today_at("14:30") <= now() <= today_at("23:00"), "open", "closed") }}
        {% elif now().weekday() in (5,) %}
          {{ iif(today_at("12:00") <= now() <= today_at("20:00"), "open", "closed") }}
        {% elif now().weekday() in (6,)%}
          {{ iif(today_at("12:00") <= now() <= today_at("20:00"), "open", "closed") }}
        {% endif %}
