- platform: scrape
  resource: https://www.boulderado.de/boulderadoweb/gym-clientcounter/index.php?mode=get&token=eyJhbGciOiJIUzI1NiIsICJ0eXAiOiJKV1QifQ.eyJjdXN0b21lciI6IkNhbXB1c0JIIn0.ppndrOlwdq9MWNVqhKdhm4KuOXJlFi7Tld2ocLbjeMw
  name: Boulderado Gym Slots Used
  select: 'div.actcounter'
  attribute: 'data-value'
  unit_of_measurement: 'people'
  value_template: '{{ iif(is_state("sensor.boulderado_gym_opening", "open"), max(0, int(value)), "unknown") }}'

- platform: scrape
  resource: https://www.boulderado.de/boulderadoweb/gym-clientcounter/index.php?mode=get&token=eyJhbGciOiJIUzI1NiIsICJ0eXAiOiJKV1QifQ.eyJjdXN0b21lciI6IkNhbXB1c0JIIn0.ppndrOlwdq9MWNVqhKdhm4KuOXJlFi7Tld2ocLbjeMw
  name: Boulderado Gym Slots Free
  select: 'div.freecounter'
  attribute: 'data-value'
  unit_of_measurement: 'people'
  value_template: '{{ iif(is_state("sensor.boulderado_gym_opening", "open"), max(0, int(value)), "unknown") }}'

- platform: template
  sensors:
    boulderado_gym_occupancy:
      friendly_name: Boulderado Gym Occupancy
      value_template: >-
        {% set used = states("sensor.boulderado_gym_slots_used") | int("unknown") %}
        {% if used != "unknown" %}
          {{ (used / 100 * 100) | round(0) }}
        {% else %}
          unknown
        {% endif %}
      unit_of_measurement: '%'

- platform: template
  sensors:
    boulderado_gym_opening:
      friendly_name: Boulderado Gym Opening
      value_template: >-
        {% if now().weekday() in (0,) %}
          {{ iif(today_at("14:30") <= now() <= today_at("23:00"), "open", "closed") }}
        {% elif now().weekday() in (1,) %}
          {{ iif(today_at("14:30") <= now() <= today_at("23:00"), "open", "closed") }}
        {% elif now().weekday() in (2,) %}
          {{ iif(today_at("14:30") <= now() <= today_at("23:00"), "open", "closed") }}
        {% elif now().weekday() in (3,) %}
          {{ iif(today_at("14:30") <= now() <= today_at("23:00"), "open", "closed") }}
        {% elif now().weekday() in (4,) %}
          {{ iif(today_at("14:30") <= now() <= today_at("23:00"), "open", "closed") }}
        {% elif now().weekday() in (5,) %}
          {{ iif(today_at("12:00") <= now() <= today_at("20:00"), "open", "closed") }}
        {% elif now().weekday() in (6,)%}
          {{ iif(today_at("12:00") <= now() <= today_at("20:00"), "open", "closed") }}
        {% endif %}
