- platform: dwd_pollen
  partregion_ids:
    - 41
  include_days:
    - today
    - tomorrow

- platform: template
  sensors:
    dwd_pollen_today_41_ambrosia:
      unit_of_measurement: "%"
      value_template: >-
        {% set state = states("sensor.dwd_pollen_41_today_ambrosia") | int(-1) %}
        {% if state != (-1) %}
          {{ (state / 6 * 100) | round(0) }}
        {% else %}
          unknown
        {% endif %}
      icon_template: >-
        mdi:flower-outline
    dwd_pollen_today_41_grass:
      unit_of_measurement: "%"
      value_template: >-
        {% set state = states("sensor.dwd_pollen_41_today_graeser") | int(-1) %}
        {% if state != (-1) %}
          {{ (state / 6 * 100) | round(0) }}
        {% else %}
          unknown
        {% endif %}
      icon_template: >-
        mdi:flower-outline
    dwd_pollen_today_41_tree:
      unit_of_measurement: "%"
      value_template: >-
        {% set states = states("sensor.dwd_pollen_41_today_beifuss") | int(-1),
                        states("sensor.dwd_pollen_41_today_birke") | int(-1),
                        states("sensor.dwd_pollen_41_today_erle") | int(-1),
                        states("sensor.dwd_pollen_41_today_esche") | int(-1),
                        states("sensor.dwd_pollen_41_today_hasel") | int(-1),
                        states("sensor.dwd_pollen_41_today_roggen") | int(-1) %}
        {% if (-1) not in states %}
          {{ ((states | max) / 6 * 100) | round(0) }}
        {% else %}
          unknown
        {% endif %}
      icon_template: >-
        mdi:flower-outline
    dwd_pollen_tomorrow_41_ambrosia:
      unit_of_measurement: "%"
      value_template: >-
        {% set state = states("sensor.dwd_pollen_41_tomorrow_ambrosia") | int(-1) %}
        {% if state != (-1) %}
          {{ (state / 6 * 100) | round(0) }}
        {% else %}
          unknown
        {% endif %}
      icon_template: >-
        mdi:flower-outline
    dwd_pollen_tomorrow_41_grass:
      unit_of_measurement: "%"
      value_template: >-
        {% set state = states("sensor.dwd_pollen_41_tomorrow_graeser") | int(-1) %}
        {% if state != (-1) %}
          {{ (state / 6 * 100) | round(0) }}
        {% else %}
          unknown
        {% endif %}
      icon_template: >-
        mdi:flower-outline
    dwd_pollen_tomorrow_41_tree:
      unit_of_measurement: "%"
      value_template: >-
        {% set states = states("sensor.dwd_pollen_41_tomorrow_beifuss") | int(-1),
                        states("sensor.dwd_pollen_41_tomorrow_birke") | int(-1),
                        states("sensor.dwd_pollen_41_tomorrow_erle") | int(-1),
                        states("sensor.dwd_pollen_41_tomorrow_esche") | int(-1),
                        states("sensor.dwd_pollen_41_tomorrow_hasel") | int(-1),
                        states("sensor.dwd_pollen_41_tomorrow_roggen") | int(-1) %}
        {% if (-1) not in states %}
          {{ ((states | max) / 6 * 100) | round(0) }}
        {% else %}
          unknown
        {% endif %}
      icon_template: >-
        mdi:flower-outline
