- platform: mqtt
  name: 'Outdoor Frontdoor Light Last Boot'
  state_topic: 'smarty/esp8266-377332/$system'
  value_template: "{{ (as_timestamp(now()) - value_json.uptime) | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', false) }}"
  expire_after: '660'
  device_class: timestamp
  availability_topic: 'smarty/esp8266-377332/$online'
  payload_available: 'true'
  payload_not_available: 'false'
- platform: mqtt
  name: 'Outdoor Frontdoor Light Firmware'
  state_topic: 'smarty/esp8266-377332/$system'
  value_template: '{{ value_json["firmware"]["version"] }}'
  expire_after: '660'
  availability_topic: 'smarty/esp8266-377332/$online'
  payload_available: 'true'
  payload_not_available: 'false'
- platform: mqtt
  name: 'Outdoor Frontdoor Light WiFi RSSI'
  state_topic: 'smarty/esp8266-377332/$system'
  value_template: '{{ (float(value_json["wifi"]["rssi"]) + 100) * 2 }}'
  unit_of_measurement: '%'
  expire_after: '660'
  availability_topic: 'smarty/esp8266-377332/$online'
  payload_available: 'true'
  payload_not_available: 'false'
- platform: mqtt
  name: 'Outdoor Frontdoor Light WiFi IP'
  state_topic: 'smarty/esp8266-377332/$system'
  value_template: '{{ value_json["wifi"]["ip"] }}'
  expire_after: '660'
  availability_topic: 'smarty/esp8266-377332/$online'
  payload_available: 'true'
  payload_not_available: 'false'

- platform: mqtt
  name: 'Outdoor Backdoor Light Last Boot'
  state_topic: 'smarty/esp8266-3dbc1d/$system'
  value_template: "{{ (as_timestamp(now()) - value_json.uptime) | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', false) }}"
  expire_after: '660'
  device_class: timestamp
  availability_topic: 'smarty/esp8266-3dbc1d/$online'
  payload_available: 'true'
  payload_not_available: 'false'
- platform: mqtt
  name: 'Outdoor Backdoor Light Firmware'
  state_topic: 'smarty/esp8266-3dbc1d/$system'
  value_template: '{{ value_json["firmware"]["version"] }}'
  expire_after: '660'
  availability_topic: 'smarty/esp8266-3dbc1d/$online'
  payload_available: 'true'
  payload_not_available: 'false'
- platform: mqtt
  name: 'Outdoor Backdoor Light WiFi RSSI'
  state_topic: 'smarty/esp8266-3dbc1d/$system'
  value_template: '{{ (float(value_json["wifi"]["rssi"]) + 100) * 2 }}'
  unit_of_measurement: '%'
  expire_after: '660'
  availability_topic: 'smarty/esp8266-3dbc1d/$online'
  payload_available: 'true'
  payload_not_available: 'false'
- platform: mqtt
  name: 'Outdoor Backdoor Light WiFi IP'
  state_topic: 'smarty/esp8266-3dbc1d/$system'
  value_template: '{{ value_json["wifi"]["ip"] }}'
  expire_after: '660'
  availability_topic: 'smarty/esp8266-3dbc1d/$online'
  payload_available: 'true'
  payload_not_available: 'false'

- platform: mqtt
  name: 'Kitchen Ceiling Light Last Boot'
  state_topic: 'smarty/esp8266-376566/$system'
  value_template: "{{ (as_timestamp(now()) - value_json.uptime) | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', false) }}"
  expire_after: '660'
  device_class: timestamp
  availability_topic: 'smarty/esp8266-376566/$online'
  payload_available: 'true'
  payload_not_available: 'false'
- platform: mqtt
  name: 'Kitchen Ceiling Light Firmware'
  state_topic: 'smarty/esp8266-376566/$system'
  value_template: '{{ value_json["firmware"]["version"] }}'
  expire_after: '660'
  availability_topic: 'smarty/esp8266-376566/$online'
  payload_available: 'true'
  payload_not_available: 'false'
- platform: mqtt
  name: 'Kitchen Ceiling Light WiFi RSSI'
  state_topic: 'smarty/esp8266-376566/$system'
  value_template: '{{ (float(value_json["wifi"]["rssi"]) + 100) * 2 }}'
  unit_of_measurement: '%'
  expire_after: '660'
  availability_topic: 'smarty/esp8266-376566/$online'
  payload_available: 'true'
  payload_not_available: 'false'
- platform: mqtt
  name: 'Kitchen Ceiling Light WiFi IP'
  state_topic: 'smarty/esp8266-376566/$system'
  value_template: '{{ value_json["wifi"]["ip"] }}'
  expire_after: '660'
  availability_topic: 'smarty/esp8266-376566/$online'
  payload_available: 'true'
  payload_not_available: 'false'

- platform: mqtt
  name: 'Kitchen Sideboard Light Last Boot'
  state_topic: 'smarty/esp8266-9541f4/$system'
  value_template: "{{ (as_timestamp(now()) - value_json.uptime) | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', false) }}"
  expire_after: '660'
  device_class: timestamp
  availability_topic: 'smarty/esp8266-9541f4/$online'
  payload_available: 'true'
  payload_not_available: 'false'
- platform: mqtt
  name: 'Kitchen Sideboard Light Firmware'
  state_topic: 'smarty/esp8266-9541f4/$system'
  value_template: '{{ value_json["firmware"]["version"] }}'
  expire_after: '660'
  availability_topic: 'smarty/esp8266-9541f4/$online'
  payload_available: 'true'
  payload_not_available: 'false'
- platform: mqtt
  name: 'Kitchen Sideboard Light WiFi RSSI'
  state_topic: 'smarty/esp8266-9541f4/$system'
  value_template: '{{ (float(value_json["wifi"]["rssi"]) + 100) * 2 }}'
  unit_of_measurement: '%'
  expire_after: '660'
  availability_topic: 'smarty/esp8266-9541f4/$online'
  payload_available: 'true'
  payload_not_available: 'false'
- platform: mqtt
  name: 'Kitchen Sideboard Light WiFi IP'
  state_topic: 'smarty/esp8266-9541f4/$system'
  value_template: '{{ value_json["wifi"]["ip"] }}'
  expire_after: '660'
  availability_topic: 'smarty/esp8266-9541f4/$online'
  payload_available: 'true'
  payload_not_available: 'false'

- platform: mqtt
  name: 'Kitchen Cabinet Light Last Boot'
  state_topic: 'smarty/esp8266-f94d00/$system'
  value_template: "{{ (as_timestamp(now()) - value_json.uptime) | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', false) }}"
  expire_after: '660'
  device_class: timestamp
  availability_topic: 'smarty/esp8266-f94d00/$online'
  payload_available: 'true'
  payload_not_available: 'false'
- platform: mqtt
  name: 'Kitchen Cabinet Light Firmware'
  state_topic: 'smarty/esp8266-f94d00/$system'
  value_template: '{{ value_json["firmware"]["version"] }}'
  expire_after: '660'
  availability_topic: 'smarty/esp8266-f94d00/$online'
  payload_available: 'true'
  payload_not_available: 'false'
- platform: mqtt
  name: 'Kitchen Cabinet Light WiFi RSSI'
  state_topic: 'smarty/esp8266-f94d00/$system'
  value_template: '{{ (float(value_json["wifi"]["rssi"]) + 100) * 2 }}'
  unit_of_measurement: '%'
  expire_after: '660'
  availability_topic: 'smarty/esp8266-f94d00/$online'
  payload_available: 'true'
  payload_not_available: 'false'
- platform: mqtt
  name: 'Kitchen Cabinet Light WiFi IP'
  state_topic: 'smarty/esp8266-f94d00/$system'
  value_template: '{{ value_json["wifi"]["ip"] }}'
  expire_after: '660'
  availability_topic: 'smarty/esp8266-f94d00/$online'
  payload_available: 'true'
  payload_not_available: 'false'

- platform: mqtt
  name: 'Living Room Ceiling Light Last Boot'
  state_topic: 'smarty/esp8266-826269/$system'
  value_template: "{{ (as_timestamp(now()) - value_json.uptime) | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', false) }}"
  expire_after: '660'
  device_class: timestamp
  availability_topic: 'smarty/esp8266-826269/$online'
  payload_available: 'true'
  payload_not_available: 'false'
- platform: mqtt
  name: 'Living Room Ceiling Light Firmware'
  state_topic: 'smarty/esp8266-826269/$system'
  value_template: '{{ value_json["firmware"]["version"] }}'
  expire_after: '660'
  availability_topic: 'smarty/esp8266-826269/$online'
  payload_available: 'true'
  payload_not_available: 'false'
- platform: mqtt
  name: 'Living Room Ceiling Light WiFi RSSI'
  state_topic: 'smarty/esp8266-826269/$system'
  value_template: '{{ (float(value_json["wifi"]["rssi"]) + 100) * 2 }}'
  unit_of_measurement: '%'
  expire_after: '660'
  availability_topic: 'smarty/esp8266-826269/$online'
  payload_available: 'true'
  payload_not_available: 'false'
- platform: mqtt
  name: 'Living Room Ceiling Light WiFi IP'
  state_topic: 'smarty/esp8266-826269/$system'
  value_template: '{{ value_json["wifi"]["ip"] }}'
  expire_after: '660'
  availability_topic: 'smarty/esp8266-826269/$online'
  payload_available: 'true'
  payload_not_available: 'false'

- platform: mqtt
  name: 'Living Room Sofa Light Last Boot'
  state_topic: 'smarty/esp8266-afc031/$system'
  value_template: "{{ (as_timestamp(now()) - value_json.uptime) | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', false) }}"
  expire_after: '660'
  device_class: timestamp
  availability_topic: 'smarty/esp8266-afc031/$online'
  payload_available: 'true'
  payload_not_available: 'false'
- platform: mqtt
  name: 'Living Room Sofa Light Firmware'
  state_topic: 'smarty/esp8266-afc031/$system'
  value_template: '{{ value_json["firmware"]["version"] }}'
  expire_after: '660'
  availability_topic: 'smarty/esp8266-afc031/$online'
  payload_available: 'true'
  payload_not_available: 'false'
- platform: mqtt
  name: 'Living Room Sofa Light WiFi RSSI'
  state_topic: 'smarty/esp8266-afc031/$system'
  value_template: '{{ (float(value_json["wifi"]["rssi"]) + 100) * 2 }}'
  unit_of_measurement: '%'
  expire_after: '660'
  availability_topic: 'smarty/esp8266-afc031/$online'
  payload_available: 'true'
  payload_not_available: 'false'
- platform: mqtt
  name: 'Living Room Sofa Light WiFi IP'
  state_topic: 'smarty/esp8266-afc031/$system'
  value_template: '{{ value_json["wifi"]["ip"] }}'
  expire_after: '660'
  availability_topic: 'smarty/esp8266-afc031/$online'
  payload_available: 'true'
  payload_not_available: 'false'

- platform: mqtt
  name: 'Bedroom Ceiling Light Last Boot'
  state_topic: 'smarty/esp8266-3e7098/$system'
  value_template: "{{ (as_timestamp(now()) - value_json.uptime) | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', false) }}"
  expire_after: '660'
  device_class: timestamp
  availability_topic: 'smarty/esp8266-3e7098/$online'
  payload_available: 'true'
  payload_not_available: 'false'
- platform: mqtt
  name: 'Bedroom Ceiling Light Firmware'
  state_topic: 'smarty/esp8266-3e7098/$system'
  value_template: '{{ value_json["firmware"]["version"] }}'
  expire_after: '660'
  availability_topic: 'smarty/esp8266-3e7098/$online'
  payload_available: 'true'
  payload_not_available: 'false'
- platform: mqtt
  name: 'Bedroom Ceiling Light WiFi RSSI'
  state_topic: 'smarty/esp8266-3e7098/$system'
  value_template: '{{ (float(value_json["wifi"]["rssi"]) + 100) * 2 }}'
  unit_of_measurement: '%'
  expire_after: '660'
  availability_topic: 'smarty/esp8266-3e7098/$online'
  payload_available: 'true'
  payload_not_available: 'false'
- platform: mqtt
  name: 'Bedroom Ceiling Light WiFi IP'
  state_topic: 'smarty/esp8266-3e7098/$system'
  value_template: '{{ value_json["wifi"]["ip"] }}'
  expire_after: '660'
  availability_topic: 'smarty/esp8266-3e7098/$online'
  payload_available: 'true'
  payload_not_available: 'false'

- platform: mqtt
  name: 'Bedroom Bed Light Last Boot'
  state_topic: 'smarty/esp8266-95791a/$system'
  value_template: "{{ (as_timestamp(now()) - value_json.uptime) | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', false) }}"
  expire_after: '660'
  device_class: timestamp
  availability_topic: 'smarty/esp8266-95791a/$online'
  payload_available: 'true'
  payload_not_available: 'false'
- platform: mqtt
  name: 'Bedroom Bed Light Firmware'
  state_topic: 'smarty/esp8266-95791a/$system'
  value_template: '{{ value_json["firmware"]["version"] }}'
  expire_after: '660'
  availability_topic: 'smarty/esp8266-95791a/$online'
  payload_available: 'true'
  payload_not_available: 'false'
- platform: mqtt
  name: 'Bedroom Bed Light WiFi RSSI'
  state_topic: 'smarty/esp8266-95791a/$system'
  value_template: '{{ (float(value_json["wifi"]["rssi"]) + 100) * 2 }}'
  unit_of_measurement: '%'
  expire_after: '660'
  availability_topic: 'smarty/esp8266-95791a/$online'
  payload_available: 'true'
  payload_not_available: 'false'
- platform: mqtt
  name: 'Bedroom Bed Light WiFi IP'
  state_topic: 'smarty/esp8266-95791a/$system'
  value_template: '{{ value_json["wifi"]["ip"] }}'
  expire_after: '660'
  availability_topic: 'smarty/esp8266-95791a/$online'
  payload_available: 'true'
  payload_not_available: 'false'

- platform: mqtt
  name: 'Bedroom Ambient Light Last Boot'
  state_topic: 'smarty/esp8266-95d69b/$system'
  value_template: "{{ (as_timestamp(now()) - value_json.uptime) | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', false) }}"
  expire_after: '660'
  device_class: timestamp
  availability_topic: 'smarty/esp8266-95d69b/$online'
  payload_available: 'true'
  payload_not_available: 'false'
- platform: mqtt
  name: 'Bedroom Ambient Light Firmware'
  state_topic: 'smarty/esp8266-95d69b/$system'
  value_template: '{{ value_json["firmware"]["version"] }}'
  expire_after: '660'
  availability_topic: 'smarty/esp8266-95d69b/$online'
  payload_available: 'true'
  payload_not_available: 'false'
- platform: mqtt
  name: 'Bedroom Ambient Light WiFi RSSI'
  state_topic: 'smarty/esp8266-95d69b/$system'
  value_template: '{{ (float(value_json["wifi"]["rssi"]) + 100) * 2 }}'
  unit_of_measurement: '%'
  expire_after: '660'
  availability_topic: 'smarty/esp8266-95d69b/$online'
  payload_available: 'true'
  payload_not_available: 'false'
- platform: mqtt
  name: 'Bedroom Ambient Light WiFi IP'
  state_topic: 'smarty/esp8266-95d69b/$system'
  value_template: '{{ value_json["wifi"]["ip"] }}'
  expire_after: '660'
  availability_topic: 'smarty/esp8266-95d69b/$online'
  payload_available: 'true'
  payload_not_available: 'false'

- platform: mqtt
  name: 'Hall Ceiling Light Last Boot'
  state_topic: 'smarty/esp8266-121bb3/$system'
  value_template: "{{ (as_timestamp(now()) - value_json.uptime) | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', false) }}"
  expire_after: '660'
  device_class: timestamp
  availability_topic: 'smarty/esp8266-121bb3/$online'
  payload_available: 'true'
  payload_not_available: 'false'
- platform: mqtt
  name: 'Hall Ceiling Light Firmware'
  state_topic: 'smarty/esp8266-121bb3/$system'
  value_template: '{{ value_json["firmware"]["version"] }}'
  expire_after: '660'
  availability_topic: 'smarty/esp8266-121bb3/$online'
  payload_available: 'true'
  payload_not_available: 'false'
- platform: mqtt
  name: 'Hall Ceiling Light WiFi RSSI'
  state_topic: 'smarty/esp8266-121bb3/$system'
  value_template: '{{ (float(value_json["wifi"]["rssi"]) + 100) * 2 }}'
  unit_of_measurement: '%'
  expire_after: '660'
  availability_topic: 'smarty/esp8266-121bb3/$online'
  payload_available: 'true'
  payload_not_available: 'false'
- platform: mqtt
  name: 'Hall Ceiling Light WiFi IP'
  state_topic: 'smarty/esp8266-121bb3/$system'
  value_template: '{{ value_json["wifi"]["ip"] }}'
  expire_after: '660'
  availability_topic: 'smarty/esp8266-121bb3/$online'
  payload_available: 'true'
  payload_not_available: 'false'
