- platform: influxdb
  host: !secret influxdb_host
  username: !secret influxdb_username
  password: !secret influxdb_password
  queries:
    - name: influxdb pi load1
      group_function: last
      where: '"host" = ''raspberrypi'''
      measurement: '"system"'
      field: load1
      database: telegraf
    - name: influxdb pi load5
      group_function: last
      where: '"host" = ''raspberrypi'''
      measurement: '"system"'
      field: load5
      database: telegraf
    - name: influxdb pi load15
      group_function: last
      where: '"host" = ''raspberrypi'''
      measurement: '"system"'
      field: load15
      database: telegraf
    - name: influxdb pi cpu usage
      value_template: '{{ (100 - value | float) | round() }}'
      group_function: last
      where: '"host" = ''raspberrypi'' and "cpu" = ''cpu-total'''
      measurement: '"cpu"'
      field: usage_idle
      database: telegraf
    - name: influxdb pi memory usage
      value_template: '{{ (100 - value | float) | round() }}'
      group_function: last
      where: '"host" = ''raspberrypi'''
      measurement: '"mem"'
      field: available_percent
      database: telegraf
    - name: influxdb pi uptime
      group_function: last
      where: '"host" = ''raspberrypi'''
      measurement: '"system"'
      field: uptime
      database: telegraf

- platform: influxdb
  host: !secret influxdb_host
  username: !secret influxdb_username
  password: !secret influxdb_password
  queries:
    - name: influxdb fritzbox link status
      group_function: last
      where: 'true'
      measurement: '"fritzbox"'
      field: physicallinkstatus
      database: telegraf
    - name: influxdb fritzbox connection status
      group_function: last
      where: 'true'
      measurement: '"fritzbox"'
      field: connectionstatus
      database: telegraf
    - name: influxdb fritzbox uptime
      group_function: last
      where: 'true'
      measurement: '"fritzbox"'
      field: uptime
      database: telegraf
    - name: influxdb fritzbox external ip address
      group_function: last
      where: 'true'
      measurement: '"fritzbox"'
      field: externalipaddress
      database: telegraf
    - name: influxdb fritzbox total bytes received
      value_template: '{{ value | filesizeformat }}'
      group_function: sum
      where: 'true'
      measurement: '(SELECT non_negative_difference(max("x_avm_de_totalbytesreceived64")) FROM "fritzbox" WHERE time > now() - 24h GROUP BY time(15m))'
      field: non_negative_difference
      database: telegraf
    - name: influxdb fritzbox total bytes sent
      value_template: '{{ value | filesizeformat }}'
      group_function: sum
      where: 'true'
      measurement: '(SELECT non_negative_difference(max("x_avm_de_totalbytessent64")) FROM "fritzbox" WHERE time > now() - 24h GROUP BY time(15m))'
      field: non_negative_difference
      database: telegraf
    - name: influxdb fritzbox transmission rate down
      value_template: '{{ value | filesizeformat }}'
      group_function: last
      where: 'true'
      measurement: '"fritzbox"'
      field: bytereceiverate
      database: telegraf
    - name: influxdb fritzbox transmission rate up
      value_template: '{{ value | filesizeformat }}'
      group_function: last
      where: 'true'
      measurement: '"fritzbox"'
      field: bytesendrate
      database: telegraf

- platform: template
  sensors:
    influxdb_fritzbox_last_reconnect:
      value_template: "{{ (as_timestamp(states.sensor.influxdb_fritzbox_uptime.last_changed) - states.sensor.influxdb_fritzbox_uptime.state | float) | timestamp_utc }}"
      icon_template: mdi:clock
      device_class: timestamp
    influxdb_pi_last_boot:
      value_template: "{{ (as_timestamp(states.sensor.influxdb_pi_uptime.last_changed) - states.sensor.influxdb_pi_uptime.state | float) | timestamp_utc }}"
      icon_template: mdi:clock
      device_class: timestamp
