- platform: uptime
  unit_of_measurement: minutes

- platform: fritzbox_netmonitor

- platform: influxdb
  host: !secret influxdb_host
  username: !secret influxdb_username
  password: !secret influxdb_password
  queries:
    - name: influxdb pi load1
      group_function: last
      where: '"host" = ''raspberrypi'''
      measurement: '"system"'
      field: load1
      database: telegraf
    - name: influxdb pi load5
      group_function: last
      where: '"host" = ''raspberrypi'''
      measurement: '"system"'
      field: load5
      database: telegraf
    - name: influxdb pi load15
      group_function: last
      where: '"host" = ''raspberrypi'''
      measurement: '"system"'
      field: load15
      database: telegraf
    - name: influxdb pi cpu usage
      value_template: '{{ (100 - value | float) | round() }}'
      group_function: last
      where: '"host" = ''raspberrypi'' and "cpu" = ''cpu-total'''
      measurement: '"cpu"'
      field: usage_idle
      database: telegraf
    - name: influxdb pi memory usage
      value_template: '{{ (100 - value | float) | round() }}'
      group_function: last
      where: '"host" = ''raspberrypi'''
      measurement: '"mem"'
      field: available_percent
      database: telegraf
    - name: influxdb pi last boot
      value_template: '{{ (as_timestamp(now()) - value | int) | timestamp_custom("%Y-%m-%dT%H:%M:%SZ", false) }}'
      group_function: last
      where: '"host" = ''raspberrypi'''
      measurement: '"system"'
      field: uptime
      database: telegraf

- platform: template
  sensors:
    hass_last_boot:
      value_template: "{{ (as_timestamp(now()) - (states.sensor.uptime.state | float * 60) ) | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', false) }}"
      icon_template: mdi:clock
      device_class: timestamp

- platform: template
  sensors:
    fritz_last_reconnect:
      value_template: "{{ (as_timestamp(now()) - states.sensor.fritz_netmonitor.attributes.uptime) | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', false) }}"
      icon_template: mdi:clock
      device_class: timestamp
    fritz_external_ip:
      value_template: '{{ states.sensor.fritz_netmonitor.attributes.external_ip }}'
      icon_template: mdi:wan
    fritz_bytes_received:
      value_template: '{{ states.sensor.fritz_netmonitor.attributes.bytes_received | filesizeformat }}'
      icon_template: mdi:download-network
    fritz_bytes_sent:
      value_template: '{{ states.sensor.fritz_netmonitor.attributes.bytes_sent | filesizeformat }}'
      icon_template: mdi:upload-network
    fritz_transmission_rate_down:
      value_template: '{{ states.sensor.fritz_netmonitor.attributes.transmission_rate_down | filesizeformat }}'
      icon_template: mdi:download-network
    fritz_transmission_rate_up:
      value_template: '{{ states.sensor.fritz_netmonitor.attributes.transmission_rate_up | filesizeformat}}'
      icon_template: mdi:upload-network
