- platform: uptime
  unit_of_measurement: minutes

- platform: influxdb
  host: !secret influxdb_host
  username: !secret influxdb_username
  password: !secret influxdb_password
  queries:
    - name: influxdb pi load1
      group_function: last
      where: '"host" = ''raspberrypi'''
      measurement: '"system"'
      field: load1
      database: telegraf
    - name: influxdb pi load5
      group_function: last
      where: '"host" = ''raspberrypi'''
      measurement: '"system"'
      field: load5
      database: telegraf
    - name: influxdb pi load15
      group_function: last
      where: '"host" = ''raspberrypi'''
      measurement: '"system"'
      field: load15
      database: telegraf
    - name: influxdb pi cpu usage
      value_template: '{{ (100 - value | float) | round() }}'
      group_function: last
      where: '"host" = ''raspberrypi'' and "cpu" = ''cpu-total'''
      measurement: '"cpu"'
      field: usage_idle
      database: telegraf
    - name: influxdb pi memory usage
      value_template: '{{ (100 - value | float) | round() }}'
      group_function: last
      where: '"host" = ''raspberrypi'''
      measurement: '"mem"'
      field: available_percent
      database: telegraf
    - name: influxdb pi last boot
      value_template: '{{ (as_timestamp(now()) - value | int) | timestamp_custom("%Y-%m-%dT%H:%M:%SZ", false) }}'
      group_function: last
      where: '"host" = ''raspberrypi'''
      measurement: '"system"'
      field: uptime
      database: telegraf

- platform: influxdb
  host: !secret influxdb_host
  username: !secret influxdb_username
  password: !secret influxdb_password
  queries:
    - name: influxdb fritzbox link status
      group_function: last
      where: 'true'
      measurement: '"fritzbox"'
      field: physicallinkstatus
      database: telegraf
    - name: influxdb fritzbox connection status
      group_function: last
      where: 'true'
      measurement: '"fritzbox"'
      field: connectionstatus
      database: telegraf
    - name: influxdb fritzbox last reconnect
      value_template: '{{ (as_timestamp(now()) - value | int) | timestamp_custom("%Y-%m-%dT%H:%M:%SZ", false) }}'
      group_function: last
      where: 'true'
      measurement: '"fritzbox"'
      field: uptime
      database: telegraf
    - name: influxdb fritzbox external ip address
      group_function: last
      where: 'true'
      measurement: '"fritzbox"'
      field: externalipaddress
      database: telegraf
    - name: influxdb fritzbox total bytes received
      value_template: '{{ value | filesizeformat }}'
      group_function: sum
      where: 'true'
      measurement: '(SELECT non_negative_difference("x_avm_de_totalbytesreceived64") FROM "fritzbox" WHERE time > now() - 24h)'
      field: non_negative_difference
      database: telegraf
    - name: influxdb fritzbox total bytes sent
      value_template: '{{ value | filesizeformat }}'
      group_function: sum
      where: 'true'
      measurement: '(SELECT non_negative_difference("x_avm_de_totalbytessent64") FROM "fritzbox" WHERE time > now() - 24h)'
      field: non_negative_difference
      database: telegraf
    - name: influxdb fritzbox transmission rate down
      value_template: '{{ value | filesizeformat }}'
      group_function: last
      where: 'true'
      measurement: '"fritzbox"'
      field: bytereceiverate
      database: telegraf
    - name: influxdb fritzbox transmission rate up
      value_template: '{{ value | filesizeformat }}'
      group_function: last
      where: 'true'
      measurement: '"fritzbox"'
      field: bytesendrate
      database: telegraf

- platform: template
  sensors:
    hass_last_boot:
      value_template: "{{ (as_timestamp(now()) - (states.sensor.uptime.state | float * 60) ) | timestamp_custom('%Y-%m-%dT%H:%M:%SZ', false) }}"
      icon_template: mdi:clock
      device_class: timestamp
