- platform: uptime

- platform: systemmonitor
  resources:
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: processor_use
    - type: memory_use_percent
    - type: disk_use_percent
      arg: /
    - type: last_boot
