- platform: uptime

- platform: systemmonitor
  resources:
    - type: load_1m
    - type: load_5m
    - type: load_15m
    - type: processor_use
    - type: memory_use_percent
    - type: disk_use_percent
      arg: /
    - type: last_boot

- platform: fritzbox_netmonitor

- platform: template
  sensors:
    fritz_bytes_received:
      value_template: '{{ states.sensor.fritz_netmonitor.attributes.bytes_received | filesizeformat }}'
      icon_template: mdi:download-network
    fritz_bytes_sent:
      value_template: '{{ states.sensor.fritz_netmonitor.attributes.bytes_sent | filesizeformat }}'
      icon_template: mdi:upload-network

