- platform: aseag_next_bus
  mode: list
  stop_id: 24236
  track: "H.1"

- platform: template
  sensors:
    next_bus_time:
      unit_of_measurement: min
      value_template: >-
        {% if (states("sensor.aseag_next_bus_24236_h_1") | int(0)) >= 1 %}
          {% set departure = state_attr("sensor.aseag_next_bus_24236_h_1", "predictions")[0].departure %}
          {{ ((as_timestamp(departure) - as_timestamp(now())) / 60) | round(0) }}
        {% else %}
          unknown
        {% endif %}
      icon_template: >-
        mdi:bus-clock

- platform: tankerkoenig
  api_key: !secret tankerkoenig_api_key
  fuel_type: 'diesel'

- platform: template
  sensors:
    gas_station_price:
      unit_of_measurement: €
      value_template: >-
        {% set price = states('sensor.tankerkoenig') %}
        {% if price != "unknown" %}
          {{ price }}
        {% else %}
          unknown
        {% endif %}
      icon_template: >-
        mdi:gas-station
    gas_station_brand:
      value_template: >-
        {% set brand = state_attr('sensor.tankerkoenig', 'brand') %}
        {% if brand != None %}
          {{ brand }}
        {% else %}
          unknown
        {% endif %}
      icon_template: >-
        mdi:gas-station
    gas_station_address:
      value_template: >-
        {% set address = state_attr('sensor.tankerkoenig', 'address') %}
        {% if address != None %}
          {{ address }}
        {% else %}
          unknown
        {% endif %}
      icon_template: >-
        mdi:gas-station

- platform: tier_nearest_scooter
  api_key: !secret tier_api_key

- platform: template
  sensors:
    nearest_scooter_distance:
      unit_of_measurement: m
      value_template: >-
        {% set distance = states('sensor.tier_nearest_scooter') %}
        {% if distance != "unknown" %}
          {{ distance }}
        {% else %}
          unknown
        {% endif %}
      icon_template: >-
        mdi:scooter
    nearest_scooter_battery:
      unit_of_measurement: '%'
      value_template: >-
        {% set battery = state_attr('sensor.tier_nearest_scooter', 'battery_level') %}
        {% if battery != None %}
          {{ battery }}
        {% else %}
          unknown
        {% endif %}
      icon_template: >-
        mdi:scooter
