- alias: 'Activate Sleep Mode of Adaptive Lighting'
  id: 172a87e1-2a8b-43df-b17a-4a63d57540a4
  trigger:
    platform: state
    entity_id: input_select.bed_mode
    from: 'just on'
    to: 'on'
  action:
    service: switch.turn_on
    target:
      entity_id:
        - switch.adaptive_lighting_sleep_mode_kitchen
        - switch.adaptive_lighting_sleep_mode_living_room

- alias: 'Deactivate Sleep Mode of Adaptive Lighting'
  id: 2e3918de-b332-4787-940d-f64e5d5e8b21
  trigger:
    platform: state
    entity_id: input_select.bed_mode
    from: 'on'
    to: 'just off'
  action:
    service: switch.turn_off
    target:
      entity_id:
        - switch.adaptive_lighting_sleep_mode_kitchen
        - switch.adaptive_lighting_sleep_mode_living_room
