- alias: 'Alarm'
  id: 496e0316-b945-4f9c-a7dc-cb025d4971a9
  trigger:
    platform: state
    entity_id:
      - binary_sensor.bedroom_motion_sensor_occupancy
      - binary_sensor.bedroom_window_left_contact
      - binary_sensor.bedroom_window_right_contact
      - binary_sensor.hall_motion_sensor_occupancy
      - binary_sensor.kitchen_motion_sensor_occupancy
      - binary_sensor.living_room_motion_sensor_occupancy
      - binary_sensor.outdoor_frontdoor_contact
      - binary_sensor.outdoor_backdoor_contact
    from: 'off'
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.away_mode
        state: 'just on'
      - condition: state
        entity_id: input_select.away_mode
        state: 'on'
  action:
    - service: notify.mobile_app_iphone_von_david
      data:
        title: "Smart Home Alerts"
        message: "Something happened at home!"
    - service: script.sonos_play
      data:
        devices:
          - media_player.sonos_device_wohnzimmer
          - media_player.sonos_device_kuche
          - media_player.sonos_device_schlafzimmer
        source: http://192.168.178.10:8123/local/sounds/alarm_siren.mp3
        volume: 0.2
