- alias: 'Alarm'
  trigger:
    platform: state
    entity_id:
      - binary_sensor.bedroom_motion
      - binary_sensor.bedroom_window_left
      - binary_sensor.bedroom_window_right
      - binary_sensor.hall_motion
      - binary_sensor.kitchen_motion
      - binary_sensor.living_room_motion
      - binary_sensor.outdoor_frontdoor
      - binary_sensor.outdoor_backdoor
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.away_mode
    state: 'on'
  action:
    - service: notify.mobile_app_iphone_von_david
      data:
        title: "Smart Home Alerts"
        message: "Something happened at home!"
    - service: script.turn_on
      data:
        entity_id: script.dogbark
