- alias: 'Intrusion Alarm'
  id: 496e0316-b945-4f9c-a7dc-cb025d4971a9
  trigger:
    platform: state
    entity_id:
      - binary_sensor.bedroom_motion_sensor_occupancy
      - binary_sensor.bedroom_window_left_contact
      - binary_sensor.bedroom_window_right_contact
      - binary_sensor.hall_motion_sensor_occupancy
      - binary_sensor.kitchen_motion_sensor_occupancy
      - binary_sensor.living_room_motion_sensor_occupancy
      - binary_sensor.outdoor_frontdoor_contact
      - binary_sensor.outdoor_backdoor_contact
    from: 'off'
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.away_mode
        state: 'just on'
      - condition: state
        entity_id: input_select.away_mode
        state: 'on'
  action:
    - service: notify.mobile_app_iphone_von_david
      data:
        title: "Intrusion Alarm"
        message: "Intrusion detected at home!"
        data:
          tag: "intrusion-alarm"
          push:
            sound:
              name: default
              critical: 1
              volume: 1.0
    - service: script.sonos_play
      data:
        devices:
          - media_player.sonos_device_wohnzimmer
          - media_player.sonos_device_kuche
          - media_player.sonos_device_schlafzimmer
        source: http://192.168.178.10:8123/local/sounds/alarm_siren.mp3
        volume: 0.2

- alias: 'Water Leak Alarm'
  id: 2b33953a-560a-4344-9985-776bf654d45d
  trigger:
    platform: state
    entity_id:
      - binary_sensor.bathroom_water_leak_sensor_water_leak
    from: 'off'
    to: 'on'
  action:
    - service: notify.mobile_app_iphone_von_david
      data:
        title: "Water Leak Alarm"
        message: "Water leak detected at home!"
        data:
          tag: "water-leak-alarm"
          push:
            sound:
              name: default
              critical: 1
              volume: 1.0
    - service: script.sonos_play
      data:
        devices:
          - media_player.sonos_device_wohnzimmer
          - media_player.sonos_device_kuche
          - media_player.sonos_device_schlafzimmer
        source: http://192.168.178.10:8123/local/sounds/alarm_siren.mp3
        volume: 0.2
