- alias: 'Alarm'
  trigger:
    platform: mqtt
    topic: 'smarty/+/button1'
  condition:
    condition: state
    entity_id: input_boolean.away_mode
    state: 'on'
  action:
    - service: notify.mobile_app_iphone_von_david
      data:
        title: "Smart Home Alerts"
        message: "Something happened at home!"
    - service: script.turn_on
      data:
        entity_id: script.dogbark
