- alias: 'Arrive Home at Day'
  trigger:
    platform: state
    entity_id: device_tracker.davids_iphone_xs
    from: 'not_home'
    to: 'home'
  condition:
    condition: state
    entity_id: sensor.period_of_day
    state: 'Day'
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.away_mode
    - service: scene.turn_on
      data:
        entity_id: scene.arrive_home_at_day

- alias: 'Arrive Home at Night'
  trigger:
    platform: state
    entity_id: device_tracker.davids_iphone_xs
    from: 'not_home'
    to: 'home'
  condition:
    condition: template
    value_template: "{{ not is_state ('sensor.period_of_day', 'Day') }}"
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.away_mode
    - service: scene.turn_on
      data:
        entity_id: scene.arrive_home_at_night

- alias: 'Leave Home at Day'
  trigger:
    platform: state
    entity_id: device_tracker.davids_iphone_xs
    from: 'home'
    to: 'not_home'
  condition:
    condition: state
    entity_id: sensor.period_of_day
    state: 'Day'
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.leave_home_at_day
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.away_mode

- alias: 'Leave Home at Night'
  trigger:
    platform: state
    entity_id: device_tracker.davids_iphone_xs
    from: 'home'
    to: 'not_home'
  condition:
    condition: template
    value_template: "{{ not is_state ('sensor.period_of_day', 'Day') }}"
  action:
    - service: scene.turn_on
      data:
        entity_id: scene.leave_home_at_night
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.away_mode
