- alias: 'Arrive Home'
  id: 75338738-61ad-44f7-bc30-d2fc8597a3df
  trigger:
    platform: state
    entity_id: person.david
    from: 'not_home'
    to: 'home'
  condition:
    condition: state
    entity_id: sensor.period_of_day
    state: 'Day'
  action:
    service: input_boolean.turn_off
    target:
      entity_id: input_boolean.away_mode

- alias: 'Leave Home'
  id: 033f2144-834c-4b2a-871e-990ccc56a0c7
  trigger:
    platform: state
    entity_id: person.david
    from: 'home'
    to: 'not_home'
  action:
    service: input_boolean.turn_on
    target:
      entity_id: input_boolean.away_mode
