- alias: 'Turn Bedroom Ceiling Light on when there is Movement'
  trigger:
    platform: state
    entity_id: binary_sensor.bedroom_motion_sensor_occupancy
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.bed_mode
        state: 'off'
      - condition: or
        conditions:
          - condition: state
            entity_id: sensor.period_of_day
            state: 'Day'
          - condition: and
            conditions:
              - condition: state
                entity_id: binary_sensor.bedroom_window_left_contact
                state: 'off'
              - condition: state
                entity_id: binary_sensor.bedroom_window_right_contact
                state: 'off'
  action:
    service: light.turn_on
    entity_id: light.bedroom_ceiling_light

- alias: 'Turn Bedroom Ceiling Light off after last Movement'
  trigger:
    platform: state
    entity_id: binary_sensor.bedroom_motion_sensor_occupancy
    from: 'on'
    to: 'off'
    for:
      minutes: 1
      seconds: 30
  action:
    service: light.turn_off
    entity_id: light.bedroom_ceiling_light

- alias: 'Turn Bedroom Ceiling Light on when closing Windows and there is Movement'
  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_window_left_contact
      from: 'on'
      to: 'off'
    - platform: state
      entity_id: binary_sensor.bedroom_window_right_contact
      from: 'on'
      to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_select.bed_mode
        state: 'off'
      - condition: state
        entity_id: binary_sensor.bedroom_motion_sensor_occupancy
        state: 'on'
      - condition: state
        entity_id: binary_sensor.bedroom_window_left_contact
        state: 'off'
      - condition: state
        entity_id: binary_sensor.bedroom_window_right_contact
        state: 'off'
  action:
    service: light.turn_on
    entity_id: light.bedroom_ceiling_light

- alias: 'Turn Bedroom Ceiling Light off when opening Windows and there is Movement'
  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_window_left_contact
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.bedroom_window_right_contact
      from: 'off'
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.period_of_day
            state: 'Day'
      - condition: state
        entity_id: binary_sensor.bedroom_motion_sensor_occupancy
        state: 'on'
  action:
    service: light.turn_off
    entity_id: light.bedroom_ceiling_light

- alias: 'Turn Bedroom Bed and Dresser Lights on when going to Bed in the Night'
  trigger:
    platform: state
    entity_id: input_select.bed_mode
    from: 'off'
    to: 'just on'
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: sensor.period_of_day
        state: 'Day'
  action:
    service: light.turn_on
    entity_id:
      - light.bedroom_bed_light
      - light.bedroom_dresser_light

- alias: 'Turn Bedroom Bed and Dresser Lights off when getting out of Bed'
  trigger:
    - platform: state
      entity_id: input_select.bed_mode
      from: 'just on'
      to: 'off'
    - platform: state
      entity_id: input_select.bed_mode
      from: 'just off'
      to: 'off'
  action:
    service: light.turn_off
    entity_id:
      - light.bedroom_bed_light
      - light.bedroom_dresser_light

- alias: 'Turn Bedroom Dresser Light on when briefly leaving the Bed in the Night'
  trigger:
    platform: state
    entity_id: input_select.bed_mode
    from: 'on'
    to: 'just off'
  condition:
    condition: not
    conditions:
      - condition: state
        entity_id: sensor.period_of_day
        state: 'Day'
  action:
    service: light.turn_on
    entity_id: light.bedroom_dresser_light

- alias: 'Turn Bedroom Dresser Light off when returning to Bed'
  trigger:
    platform: state
    entity_id: input_select.bed_mode
    from: 'just off'
    to: 'on'
  action:
    service: light.turn_off
    entity_id: light.bedroom_dresser_light
