- alias: 'Enable: Say Good Morning'
  initial_state: false
  trigger:
    - platform: time
      at: '06:00:00'
  action:
    - service: automation.turn_on
      data:
        entity_id: automation.say_good_morning

- alias: 'Disable: Say Good Morning'
  initial_state: false
  trigger:
    - platform: time
      at: '12:00:00'
  action:
    - service: automation.turn_off
      data:
        entity_id: automation.say_good_morning

- alias: 'Say Good Morning'
  initial_state: false
  trigger:
    - platform: mqtt
      topic: 'smarty/esp8266-376566/button1'
    - platform: mqtt
      topic: 'smarty/esp8266-826269/button1'
  action:
    - delay: '00:00:01'
    - service: script.sonos_say
      data_template:
        sonos_say_volume: '0.3'
        sonos_say_message: >
          {{ [
          "Einen guten Morgen David!",
          "Guten Morgen David!",
          "Hallo David!"
          ] | random }}
        sonos_say_delay: '00:00:02'
    - service: automation.turn_off
      data:
        entity_id: automation.say_good_morning
