- alias: 'Turn Hall Ceiling Light on when there is Movement'
  trigger:
    platform: state
    entity_id: binary_sensor.hall_motion_sensor_occupancy
    from: 'off'
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: sensor.period_of_day
        state: 'Day'
      - condition: state
        entity_id: binary_sensor.outdoor_frontdoor_contact
        state: 'off'
  action:
    service: light.turn_on
    entity_id: light.hall_ceiling_light

- alias: 'Turn Hall Ceiling Light on when opening Door without Movement'
  trigger:
    platform: state
    entity_id: binary_sensor.outdoor_frontdoor_contact
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.period_of_day
        state: 'Day'
      - condition: state
        entity_id: binary_sensor.hall_motion_sensor_occupancy
        state: 'off'
  action:
    service: light.turn_on
    entity_id: light.hall_ceiling_light

- alias: 'Turn Hall Ceiling Light off after last Movement'
  trigger:
    platform: state
    entity_id: binary_sensor.hall_motion_sensor_occupancy
    from: 'on'
    to: 'off'
    for:
      minutes: 3
  action:
    service: light.turn_off
    entity_id: light.hall_ceiling_light

- alias: 'Turn Hall Ceiling Light on when closing Door and there is Movement'
  trigger:
    platform: state
    entity_id: binary_sensor.outdoor_frontdoor_contact
    from: 'on'
    to: 'off'
  condition:
    condition: state
    entity_id: binary_sensor.hall_motion_sensor_occupancy
    state: 'on'
  action:
    service: light.turn_on
    entity_id: light.hall_ceiling_light

- alias: 'Turn Hall Ceiling Light off when opening Door and there is Movement'
  trigger:
    platform: state
    entity_id: binary_sensor.outdoor_frontdoor_contact
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.period_of_day
            state: 'Day'
      - condition: state
        entity_id: binary_sensor.hall_motion_sensor_occupancy
        state: 'on'
  action:
    service: light.turn_off
    entity_id: light.hall_ceiling_light

- alias: 'Turn Hall Ceiling Light off when closing Door without Movement'
  trigger:
    platform: state
    entity_id: binary_sensor.outdoor_frontdoor_contact
    from: 'on'
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.period_of_day
        state: 'Day'
      - condition: state
        entity_id: binary_sensor.hall_motion_sensor_occupancy
        state: 'off'
  action:
    service: light.turn_off
    entity_id: light.hall_ceiling_light
