- alias: 'Turn Kitchen Ceiling and Counter Light on when there is Movement'
  id: 763269a9-c70f-4ae5-877e-fa35acea16fa
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion_sensor_occupancy
    from: 'off'
    to: 'on'
  action:
    service: light.turn_on
    target:
      entity_id:
        - light.kitchen_ceiling_light
        - light.kitchen_counter_light

- alias: 'Turn Kitchen Ceiling and Counter Light off after last Movement'
  id: 57517167-d96e-4ba2-ab26-b050d4084689
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion_sensor_occupancy
    from: 'on'
    to: 'off'
    for:
      minutes: 5
  action:
    service: light.turn_off
    target:
      entity_id:
        - light.kitchen_ceiling_light
        - light.kitchen_counter_light

- alias: 'Turn Kitchen Sideboard Light on'
  id: 912dcf60-5a35-4f9e-934b-c33fc5bdd16d
  trigger:
    - platform: state
      entity_id: sensor.period_of_day
      from: 'Sunset'
      to: 'Dusk'
    - platform: state
      entity_id:
        - input_select.away_mode
        - input_select.bed_mode
      from: 'on'
      to: 'just off'
  condition:
    - condition: state
      entity_id: sensor.period_of_day
      state:
        - 'Dusk'
        - 'Night'
        - 'Dawn'
    - condition: state
      entity_id: input_select.away_mode
      state:
        - 'just off'
        - 'off'
    - condition: state
      entity_id: input_select.bed_mode
      state:
        - 'just off'
        - 'off'
  action:
    service: script.random_color
    data:
      lights:
        - light.kitchen_sideboard_light

- alias: 'Turn Kitchen Sideboard Light off'
  id: 213a5359-2fc3-47bd-9876-5dc402cbd7bd
  trigger:
    - platform: state
      entity_id: sensor.period_of_day
      from: 'Dawn'
      to: 'Sunrise'
    - platform: state
      entity_id:
        - input_select.away_mode
        - input_select.bed_mode
      from:
        - 'just on'
        - 'just off'
      to: 'on'
  action:
    service: light.turn_off
    target:
      entity_id:
        - light.kitchen_sideboard_light
