- alias: 'Turn Kitchen Ceiling and Counter Light on when there is Movement'
  id: 763269a9-c70f-4ae5-877e-fa35acea16fa
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion_sensor_occupancy
    from: 'off'
    to: 'on'
  action:
    service: light.turn_on
    target:
      entity_id:
        - light.kitchen_ceiling_light
        - light.kitchen_counter_light

- alias: 'Turn Kitchen Ceiling and Counter Light off after last Movement'
  id: 57517167-d96e-4ba2-ab26-b050d4084689
  trigger:
    platform: state
    entity_id: binary_sensor.kitchen_motion_sensor_occupancy
    from: 'on'
    to: 'off'
    for:
      minutes: 5
  action:
    service: light.turn_off
    target:
      entity_id:
        - light.kitchen_ceiling_light
        - light.kitchen_counter_light

- alias: 'Turn Kitchen Lights off when going to Bed'
  id: 213a5359-2fc3-47bd-9876-5dc402cbd7bd
  trigger:
    platform: state
    entity_id: input_select.bed_mode
    from: 'just on'
    to: 'on'
  action:
    service: light.turn_off
    target:
      entity_id: group.kitchen_lights
