- alias: 'Turn Living Room Ceiling Light on when there is Movement'
  id: a9166a79-028c-40d2-b157-7dd6ec3189cb
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_motion_sensor_occupancy
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: input_select.bed_mode
    state:
      - 'on'
      - 'just on'
  action:
    service: light.turn_on
    target:
      entity_id: light.living_room_ceiling_light

- alias: 'Turn Living Room Ceiling Light off after last Movement'
  id: 8de09585-9311-457c-be0b-84f7c8142d41
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_motion_sensor_occupancy
    from: 'on'
    to: 'off'
    for:
      minutes: 5
  condition:
    condition: state
    entity_id: input_select.bed_mode
    state:
      - 'on'
      - 'just on'
  action:
    service: light.turn_off
    target:
      entity_id: light.living_room_ceiling_light

- alias: 'Turn Living Room Ceiling Light off when going to Bed'
  id: 30efc83b-a870-48bb-8341-28d821a5a33d
  trigger:
    platform: state
    entity_id: input_select.bed_mode
    from: 'just on'
    to: 'on'
  action:
    service: light.turn_off
    target:
      entity_id: light.living_room_ceiling_light

- alias: 'Turn Living Room Sofa and TV Light on'
  id: 861debaa-4310-4053-b98b-2275847691bb
  trigger:
    - platform: state
      entity_id: sensor.period_of_day
      from: 'Sunset'
      to: 'Dusk'
    - platform: state
      entity_id:
        - input_select.away_mode
        - input_select.bed_mode
      from: 'on'
      to: 'just off'
  condition:
    - condition: state
      entity_id: sensor.period_of_day
      state:
        - 'Dusk'
        - 'Night'
        - 'Dawn'
    - condition: state
      entity_id: input_select.away_mode
      state:
        - 'just off'
        - 'off'
    - condition: state
      entity_id: input_select.bed_mode
      state:
        - 'just off'
        - 'off'
  action:
    service: light.turn_on
    target:
      entity_id:
        - light.living_room_sofa_light
        - light.living_room_tv_light

- alias: 'Turn Living Room Sofa and TV Light off'
  id: c3dda693-5c89-453b-8ca0-647e86f7b0ba
  trigger:
    - platform: state
      entity_id: sensor.period_of_day
      from: 'Dawn'
      to: 'Sunrise'
    - platform: state
      entity_id:
        - input_select.away_mode
        - input_select.bed_mode
      from:
        - 'just on'
        - 'just off'
      to: 'on'
  action:
    service: light.turn_off
    target:
      entity_id:
        - light.living_room_sofa_light
        - light.living_room_tv_light
