- alias: 'Turn TV on'
  id: 24c4a623-0628-45ae-964a-9436f3cba4d1
  triggers:
    - trigger: device
      domain: mqtt
      device_id: 86d39ed7bb87433588884e39a14bc36d
      type: action
      subtype: brightness_move_up
  conditions:
    - condition: state
      entity_id: media_player.lg_webos_tv
      state: "off"
  actions:
    - action: media_player.turn_on
      target:
        entity_id: media_player.lg_webos_tv

- alias: 'Turn TV off'
  id: 61529196-14fc-4945-adc3-18902d77c5ff
  triggers:
    - trigger: device
      domain: mqtt
      device_id: 86d39ed7bb87433588884e39a14bc36d
      type: action
      subtype: brightness_move_down
    - platform: state
      entity_id: input_select.away_mode
      from: 'off'
      to: 'just on'
    - platform: state
      entity_id: input_select.bed_mode
      from: 'off'
      to: 'just on'
  conditions:
    - condition: state
      entity_id: media_player.lg_webos_tv
      state: "on"
  actions:
    - action: media_player.turn_off
      target:
        entity_id: media_player.lg_webos_tv

- alias: 'Turn TV Volume up'
  id: d530c1f7-008d-487a-ac04-6dcd0e8dd2fd
  triggers:
    - trigger: device
      domain: mqtt
      device_id: 86d39ed7bb87433588884e39a14bc36d
      type: action
      subtype: "on"
  conditions:
    - condition: state
      entity_id: media_player.lg_webos_tv
      state: "on"
  actions:
    - action: media_player.volume_up
      target:
        entity_id: media_player.lg_webos_tv

- alias: 'Turn TV Volume down'
  id: e2b8f04b-e7ff-45f0-8480-68cbfa1bc024
  triggers:
    - trigger: device
      domain: mqtt
      device_id: 86d39ed7bb87433588884e39a14bc36d
      type: action
      subtype: "off"
  conditions:
    - condition: state
      entity_id: media_player.lg_webos_tv
      state: "on"
  actions:
    - action: media_player.volume_down
      target:
        entity_id: media_player.lg_webos_tv

- alias: 'Turn TV Power on'
  id: 23f2cd65-f5b3-491c-a87f-2055301daa28
  triggers:
    - trigger: device
      domain: webostv
      device_id: ab25640d50b175aaff23e7a6e8459140
      type: webostv.turn_on
  condition:
    - condition: state
      entity_id: media_player.lg_webos_tv
      state: 'off'
    - condition: state
      entity_id: switch.living_room_tv
      state: 'off'
  actions:
    - service: switch.turn_on
      target:
        entity_id: switch.living_room_tv
    - delay:
        seconds: 5
    - repeat:
        sequence:
          - action: wake_on_lan.send_magic_packet
            data:
              mac: !secret wake_on_lan_mac
              broadcast_address: !secret wake_on_lan_broadcast_address
              broadcast_port: !secret wake_on_lan_broadcast_port
          - delay:
              seconds: 2
        until:
          - condition: or
            conditions:
              - condition: state
                entity_id: media_player.lg_webos_tv
                state: 'on'
              - condition: template
                value_template: "{{ repeat.index >= 10 }}"

- alias: 'Turn TV Power off'
  id: 0958a97a-3efb-468a-9c75-eee8098f39ad
  trigger:
    - platform: numeric_state
      entity_id: sensor.living_room_tv_power
      below: 5
      for:
        seconds: 30
  condition:
    - condition: state
      entity_id: media_player.lg_webos_tv
      state: 'off'
    - condition: state
      entity_id: switch.living_room_tv
      state: 'on'
  action:
    - service: switch.turn_off
      target:
        entity_id: switch.living_room_tv
