- alias: 'Turn Living Room Ceiling Light on when there is Movement'
  id: a9166a79-028c-40d2-b157-7dd6ec3189cb
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_motion_sensor_occupancy
    from: 'off'
    to: 'on'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.bed_mode
        state: 'on'
      - condition: state
        entity_id: input_select.bed_mode
        state: 'just on'
  action:
    service: light.turn_on
    target:
      entity_id: light.living_room_ceiling_light

- alias: 'Turn Living Room Ceiling Light off after last Movement'
  id: 8de09585-9311-457c-be0b-84f7c8142d41
  trigger:
    platform: state
    entity_id: binary_sensor.living_room_motion_sensor_occupancy
    from: 'on'
    to: 'off'
    for:
      minutes: 5
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.bed_mode
        state: 'on'
      - condition: state
        entity_id: input_select.bed_mode
        state: 'just on'
  action:
    service: light.turn_off
    target:
      entity_id: light.living_room_ceiling_light

- alias: 'Turn Living Room Lights off when going to Bed'
  id: 30efc83b-a870-48bb-8341-28d821a5a33d
  trigger:
    platform: state
    entity_id: input_select.bed_mode
    from: 'just on'
    to: 'on'
  action:
    service: light.turn_off
    target:
      entity_id: group.living_room_lights
