- alias: 'Send Notification about Open Doors and Windows in Winter'
  trigger:
    - platform: state
      entity_id: binary_sensor.outdoor_frontdoor
      from: 'off'
      to: 'on'
      for:
        minutes: 10
    - platform: state
      entity_id: binary_sensor.outdoor_backdoor
      from: 'off'
      to: 'on'
      for:
        minutes: 10
    - platform: state
      entity_id: binary_sensor.bedroom_window_left
      from: 'off'
      to: 'on'
      for:
        minutes: 10
    - platform: state
      entity_id: binary_sensor.bedroom_window_right
      from: 'off'
      to: 'on'
      for:
        minutes: 10
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'
      - condition: state
        entity_id: sensor.season
        state: 'winter'
  action:
    service: notify.mobile_app_iphone_von_david
    data:
      title: "Open doors and windows"
      message: "Close doors or windows to keep it warm!"

- alias: 'Send Notification about Open Doors and Windows at Sunset'
  trigger:
    platform: state
    entity_id: sensor.period_of_day
    from: 'Day'
    to: 'Sunset'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'
      - condition: or
        conditions:
          - condition: state
            entity_id: binary_sensor.outdoor_frontdoor
            state: 'on'
          - condition: state
            entity_id: binary_sensor.outdoor_backdoor
            state: 'on'
          - condition: state
            entity_id: binary_sensor.bedroom_window_left
            state: 'on'
          - condition: state
            entity_id: binary_sensor.bedroom_window_right
            state: 'on'
  action:
    service: notify.mobile_app_iphone_von_david
    data:
      title: "Open doors and windows"
      message: "Close doors and windows to keep bugs out!"

- alias: 'Send Notification about high Living Room Humdity'
  trigger:
    - platform: numeric_state
      entity_id: sensor.living_room_multisensor_humidity
      above: 60
      for:
        minutes: 30
    - platform: numeric_state
      entity_id: sensor.dark_sky_humidity
      below: 60
      for:
        minutes: 30
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'
      - condition: numeric_state
        entity_id: sensor.living_room_multisensor_humidity
        above: 60
      - condition: numeric_state
        entity_id: sensor.dark_sky_humidity
        below: 60
      - condition: state
        entity_id: binary_sensor.outdoor_frontdoor
        state: 'off'
      - condition: state
        entity_id: binary_sensor.outdoor_backdoor
        state: 'off'
  action:
    service: notify.mobile_app_iphone_von_david
    data:
      title: "Humdity in living room too high"
      message: "Open doors or windows to reduce humdity!"

- alias: 'Send Notification about high Bedroom Humdity'
  trigger:
    - platform: numeric_state
      entity_id: sensor.bedroom_multisensor_humidity
      above: 60
      for:
        minutes: 30
    - platform: numeric_state
      entity_id: sensor.dark_sky_humidity
      below: 60
      for:
        minutes: 30
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'off'
      - condition: numeric_state
        entity_id: sensor.bedroom_multisensor_humidity
        above: 60
      - condition: numeric_state
        entity_id: sensor.dark_sky_humidity
        below: 60
      - condition: state
        entity_id: binary_sensor.bedroom_window_left
        state: 'off'
      - condition: state
        entity_id: binary_sensor.bedroom_window_right
        state: 'off'
  action:
    service: notify.mobile_app_iphone_von_david
    data:
      title: "Humdity in bedroom too high"
      message: "Open doors or windows to reduce humdity!"
