- alias: 'Turn Outdoor Frontdoor Light on'
  id: d5cb8c07-9327-4859-8381-783801d076fa
  trigger:
    - platform: state
      entity_id: sensor.period_of_day
      from: 'Sunset'
      to: 'Dusk'
    - platform: state
      entity_id: input_select.away_mode
      from: 'on'
      to: 'just off'
    - platform: state
      entity_id: input_select.bed_mode
      from: 'just off'
      to: 'off'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: sensor.period_of_day
          state: 'Dusk'
        - condition: state
          entity_id: sensor.period_of_day
          state: 'Night'
        - condition: state
          entity_id: sensor.period_of_day
          state: 'Dawn'
    - condition: or
      conditions:
        - condition: state
          entity_id: input_select.away_mode
          state: 'just off'
        - condition: state
          entity_id: input_select.away_mode
          state: 'off'
    - condition: state
      entity_id: input_select.bed_mode
      state: 'off'
  action:
    service: light.turn_on
    target:
      entity_id: light.outdoor_frontdoor_light

- alias: 'Turn Outdoor Frontdoor and Backdoor Light off '
  id: c3dda693-5c89-453b-8ca0-647e86f7b0ba
  trigger:
    - platform: state
      entity_id: sensor.period_of_day
      from: 'Dawn'
      to: 'Sunrise'
    - platform: state
      entity_id: input_select.away_mode
      from: 'just on'
      to: 'on'
    - platform: state
      entity_id: input_select.bed_mode
      from: 'just on'
      to: 'on'
  action:
    service: light.turn_off
    target:
      entity_id:
        - light.outdoor_frontdoor_light
        - light.outdoor_backdoor_light
