- alias: 'Turn Outdoor Frontdoor Light on'
  id: d5cb8c07-9327-4859-8381-783801d076fa
  trigger:
    - platform: state
      entity_id: input_select.away_mode
      from: 'on'
      to: 'just off'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: sensor.period_of_day
          state: 'Dusk'
        - condition: state
          entity_id: sensor.period_of_day
          state: 'Night'
        - condition: state
          entity_id: sensor.period_of_day
          state: 'Dawn'
    - condition: or
      conditions:
        - condition: state
          entity_id: input_select.away_mode
          state: 'just off'
        - condition: state
          entity_id: input_select.away_mode
          state: 'off'
    - condition: state
      entity_id: input_select.bed_mode
      state: 'off'
  action:
    service: light.turn_on
    target:
      entity_id: light.outdoor_frontdoor_light

- alias: 'Turn Outdoor Backdoor Light on'
  id: d7efe2bf-f328-44ef-9ab0-98c2e5e0ba64
  trigger:
    - platform: state
      entity_id: sensor.period_of_day
      from: 'Sunset'
      to: 'Dusk'
    - platform: state
      entity_id: input_select.away_mode
      from: 'on'
      to: 'just off'
    - platform: state
      entity_id: input_select.bed_mode
      from: 'just off'
      to: 'off'
  condition:
    - condition: or
      conditions:
        - condition: state
          entity_id: sensor.period_of_day
          state: 'Dusk'
        - condition: state
          entity_id: sensor.period_of_day
          state: 'Night'
        - condition: state
          entity_id: sensor.period_of_day
          state: 'Dawn'
    - condition: or
      conditions:
        - condition: state
          entity_id: input_select.away_mode
          state: 'just off'
        - condition: state
          entity_id: input_select.away_mode
          state: 'off'
    - condition: state
      entity_id: input_select.bed_mode
      state: 'off'
  action:
    service: light.turn_on
    target:
      entity_id: light.outdoor_backdoor_light

- alias: 'Turn Outdoor Frontdoor Light off'
  id: 20b82cc6-4c54-4ac0-b938-4659dc4a3bcd
  trigger:
    - platform: state
      entity_id: sensor.period_of_day
      from: 'Dawn'
      to: 'Sunrise'
    - platform: state
      entity_id: input_select.away_mode
      from: 'just on'
      to: 'on'
    - platform: state
      entity_id: input_select.away_mode
      from: 'just off'
      to: 'off'
    - platform: state
      entity_id: input_select.bed_mode
      from: 'just on'
      to: 'on'
  action:
    service: light.turn_off
    target:
      entity_id: light.outdoor_frontdoor_light

- alias: 'Turn Outdoor Backdoor Light off'
  id: 19f05355-6ee0-4a43-a684-cb6738a5a585
  trigger:
    - platform: state
      entity_id: sensor.period_of_day
      from: 'Dawn'
      to: 'Sunrise'
    - platform: state
      entity_id: input_select.away_mode
      from: 'just on'
      to: 'on'
    - platform: state
      entity_id: input_select.bed_mode
      from: 'just on'
      to: 'on'
  action:
    service: light.turn_off
    target:
      entity_id: light.outdoor_backdoor_light
