- alias: 'Turn Outdoor Lights on before Sunset'
  trigger:
    platform: state
    entity_id: sensor.period_of_day
    from: 'Day'
    to: 'Sunset'
  action:
    - service: light.turn_on
      target:
        entity_id: group.outdoor_lights

- alias: 'Turn Outdoor Lights on in the Night when Arriving'
  trigger:
    platform: state
    entity_id: input_boolean.away_mode
    from: 'on'
    to: 'off'
  condition:
    condition: and
    conditions:
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.period_of_day
            state: 'Day'
      - condition: time
        after: '01:00:00'
        before: '12:00:00'
  action:
    - service: light.turn_on
      target:
        entity_id: group.outdoor_lights

- alias: 'Turn Outdoor Lights off after Sunrise'
  trigger:
    platform: state
    entity_id: sensor.period_of_day
    from: 'Sunrise'
    to: 'Day'
  action:
    - service: light.turn_off
      target:
        entity_id: group.outdoor_lights

- alias: 'Turn Outdoor Lights off in the Night when Away or in Bed'
  trigger:
    platform: time
    at: '01:00:00'
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.away_mode
        state: 'on'
      - condition: state
        entity_id: input_select.bed_mode
        state: 'on'
  action:
    - service: light.turn_off
      target:
        entity_id: group.outdoor_lights

- alias: 'Turn Outdoor Lights off in the Night when Leaving'
  trigger:
    platform: state
    entity_id: input_boolean.away_mode
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: not
        conditions:
          - condition: state
            entity_id: sensor.period_of_day
            state: 'Day'
      - condition: time
        after: '01:00:00'
        before: '12:00:00'
  action:
    - service: light.turn_off
      target:
        entity_id: group.outdoor_lights

- alias: 'Turn Outdoor Lights off when going to Bed late'
  trigger:
    platform: state
    entity_id: input_select.bed_mode
    from: 'just on'
    to: 'on'
  condition:
    condition: time
    after: '01:00:00'
  action:
    service: light.turn_off
    target:
      entity_id: group.outdoor_lights
