- alias: 'Reset Sonos Volume'
  id: cef75154-16bc-4990-b1d8-00d7fe5b13d2
  mode: queued
  trigger:
    platform: state
    entity_id:
      - media_player.sonos_device_kuche
      - media_player.sonos_device_schlafzimmer
      - media_player.sonos_device_wohnzimmer
    to: 'paused'
    for:
      minutes: 5
  action:
    - service: media_player.volume_set
      target:
        entity_id: "{{ trigger.entity_id }}"
      data:
        volume_level: 0.06
    - service: media_player.volume_mute
      target:
        entity_id: "{{ trigger.entity_id }}"
      data:
        is_volume_muted: false
