- alias: 'Reset Sonos Volume'
  id: cef75154-16bc-4990-b1d8-00d7fe5b13d2
  mode: queued
  trigger:
    platform: state
    entity_id:
      - media_player.sonos_device_kuche
      - media_player.sonos_device_schlafzimmer
      - media_player.sonos_device_wohnzimmer
    to:
      - 'idle'
      - 'paused'
    for:
      minutes: 10
  action:
    - service: media_player.volume_set
      target:
        entity_id: "{{ trigger.entity_id }}"
      data:
        volume_level: 0.08
    - service: media_player.volume_mute
      target:
        entity_id: "{{ trigger.entity_id }}"
      data:
        is_volume_muted: false

- alias: 'Reset Sonos Source'
  id: 48231078-6bc7-4396-9f17-d8695a1ea491
  mode: queued
  trigger:
    platform: state
    entity_id:
      - media_player.sonos_device_kuche
      - media_player.sonos_device_schlafzimmer
      - media_player.sonos_device_wohnzimmer
    to:
      - 'idle'
      - 'paused'
    for:
      minutes: 10
  action:
    - action: media_player.select_source
      target:
        entity_id: "{{ trigger.entity_id }}"
      data:
        source: "Apple Music Hits"
    - service: media_player.media_pause
      target:
        entity_id: "{{ trigger.entity_id }}"

- alias: 'Pause Sonos'
  id: 6729b4c3-631f-4211-917b-9d110f94de0c
  mode: queued
  trigger:
    - platform: state
      entity_id: input_select.away_mode
      from: 'off'
      to: 'just on'
    - platform: state
      entity_id: input_select.bed_mode
      from: 'off'
      to: 'just on'
  action:
    - service: media_player.media_pause
      target:
        entity_id:
          - media_player.sonos_device_kuche
          - media_player.sonos_device_wohnzimmer
    - condition: state
      entity_id: input_select.away_mode
      state: 'just on'
    - service: media_player.media_pause
      target:
        entity_id: media_player.sonos_device_schlafzimmer
