- alias: 'Say Next Bus First Warning'
  initial_state: false
  trigger:
    platform: numeric_state
    entity_id: sensor.next_bus_time
    below: 16
    above: 10
  action:
    - service: script.turn_on
      data:
        entity_id: script.tts_time_to_next_bus
    - service: automation.turn_off
      data:
        entity_id:
          - automation.say_next_bus_first_warning

- alias: 'Say Next Bus Second Warning'
  initial_state: false
  trigger:
    platform: numeric_state
    entity_id: sensor.next_bus_time
    below: 11
    above: 5
  action:
    - service: script.turn_on
      data:
        entity_id: script.tts_time_to_next_bus
    - service: automation.turn_off
      data:
        entity_id:
          - automation.say_next_bus_first_warning
          - automation.say_next_bus_second_warning

- alias: 'Say Next Bus Third Warning'
  initial_state: false
  trigger:
    platform: numeric_state
    entity_id: sensor.next_bus_time
    below: 6
    above: 0
  action:
    - service: script.turn_on
      data:
        entity_id: script.tts_time_to_next_bus
    - service: automation.turn_off
      data:
        entity_id:
          - automation.say_next_bus_first_warning
          - automation.say_next_bus_second_warning
          - automation.say_next_bus_third_warning
