- alias: 'Update'
  id: cb5fe1c6-5f65-497b-91b8-514828b0f377
  trigger:
    platform: state
    entity_id: binary_sensor.updater
    from: 'off'
    to: 'on'
  action:
    service: notify.mobile_app_iphone_von_david
    data_template:
      title: "New Version of Home Assistant"
      message: "Version {{ states.binary_sensor.updater.attributes.newest_version }} of Home Assistant is now available."
