language: python
python:
  - 3.8
  - 3.9
cache:
  pip: true
  directories:
    - $HOME/.cache/pre-commit
before_install:
  - python --version
  - pip install -U pip
install:
  - pip install -r requirements_test.txt
script:
  - pre-commit install-hooks
  - pre-commit run black --all-files
  - pre-commit run flake8 --all-files
  - pre-commit run isort --all-files
