name: Lint

on:
  pull_request:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEFAULT_PYTHON: '3.11'
  DEFAULT_PYTHON_CACHE: '1'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Python
        id: python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Cache Python packages
        id: cache-python
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ steps.python.outputs.python-version }}-python-${{ env.DEFAULT_PYTHON_CACHE }}
      - name: Install pre-commit
        run: python -m pip install --upgrade --upgrade-strategy eager pre-commit
      - name: Cache pre-commit dependencies
        id: cache-precommit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-${{ steps.python.outputs.python-version }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install pre-commit dependencies
        if: steps.cache-precommit.outputs.cache-hit != 'true'
        run: pre-commit install-hooks
      - name: Run pre-commit against all files
        run: pre-commit run --all-files
