name: Lint

on:
  pull_request:
  push:
    branches:
      - master

env:
  DEFAULT_PYTHON: '3.11'
  DEFAULT_PRE_COMMIT: '3.4.0'

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Python
        id: python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Install pre-commit
        run: python -m pip install pre-commit==${{ env.DEFAULT_PRE_COMMIT }}
      - name: Cache pre-commit dependencies
        id: cache-precommit
        uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-${{ steps.python.outputs.python-version }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Install pre-commit dependencies
        if: steps.cache-precommit.outputs.cache-hit != 'true'
        run: pre-commit install-hooks
      - name: Run pre-commit against all files
        run: pre-commit run --all-files
