name: Test

on:
  pull_request:
  push:

env:
  DEFAULT_PYTHON: '3.11'

jobs:
  check-config:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: [stable, beta]
    env:
      DEFAULT_HOME_ASSISTANT: ghcr.io/home-assistant/home-assistant:${{ matrix.tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup secrets
        run: mv secrets_dummy.yaml secrets.yaml
      - name: Pull Docker image
        run: docker pull ${{ env.DEFAULT_HOME_ASSISTANT }}
      - name: Check Home Assistant configuration
        run: docker run --rm -v ${{ github.workspace }}:/config ${{ env.DEFAULT_HOME_ASSISTANT }} hass -c /config --script check_config
