name: Test

on:
  pull_request:
  push:
    branches:
      - master

env:
  DEFAULT_PYTHON: '3.11'
  DEFAULT_HOME_ASSISTANT: '2023.9.2'

jobs:
  check-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Python
        id: python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Install Home Assistant
        run: python -m pip install homeassistant==${{ env.DEFAULT_HOME_ASSISTANT }}
      - name: Setup secrets
        run: mv secrets_dummy.yaml secrets.yaml
      - name: Check Home Assistant configuration
        run: hass -c . --script check_config
